"""Generate src/dev/d3d_census.cpp: a call census of the D3D library functions (developer build).

Every recompiled function in the given ranges is wrapped with a hook that counts calls, keeps the
last call's r3-r8 as a sample, and runs the original (__imp__sub_XXXXXXXX). Every 5 s the census
logs the most-called functions per swap, which identifies draw calls, state setters and the like
from the running game instead of from reading code.

    python tools/native/gen_census.py [START END ...]     (default: the D3D library range)
    cmake -DSVR_D3D_CENSUS=ON ...                        (adds the generated file to the build)

Calls per swap use D3DDevice_Swap (sub_8225BD40) as the frame boundary.
"""

import os
import pickle
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
INDEX = os.path.join(ROOT, "logs", "recomp_index.pickle")
OUT = os.path.join(ROOT, "src", "dev", "d3d_census.cpp")
SWAP = 0x8225BD40
DEFAULT_RANGES = [(0x8224A800, 0x82278500), (0x825A3800, 0x825A5000)]  # SvR 2009
# Functions hooked by other developer files (src/dev/shader_dump.cpp); a function can have only one hook.
EXCLUDE = {0x82261170, 0x82261060}


def main():
    args = [int(a, 16) for a in sys.argv[1:]]
    ranges = list(zip(args[::2], args[1::2])) or DEFAULT_RANGES
    funcs = pickle.load(open(INDEX, "rb"))["funcs"]
    addrs = sorted(a for a in funcs if any(lo <= a < hi for lo, hi in ranges) and a not in EXCLUDE)
    assert SWAP in addrs, "the swap function must be in range (frame boundary)"
    lines = [
        "// Generated by tools/native/gen_census.py - developer call census of D3D library functions.",
        "// Only built with -DSVR_D3D_CENSUS=ON. Do not edit by hand.",
        "",
        '#include "generated/default/svr2009_init.h"',
        '#include "d3d_census_runtime.h"',
        "",
        f"static constexpr uint32_t kCensusAddrs[] = {{",
    ]
    for i in range(0, len(addrs), 6):
        lines.append("    " + ", ".join(f"0x{a:08X}" for a in addrs[i:i + 6]) + ",")
    lines += ["};", "", f"static svr_census::Census g_census(kCensusAddrs, {len(addrs)}, "
              f"{addrs.index(SWAP)});", ""]
    for i, a in enumerate(addrs):
        lines.append(f"REX_HOOK_RAW(sub_{a:08X}) {{ g_census.Hit({i}, ctx); "
                     f"__imp__sub_{a:08X}(ctx, base); }}")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"{len(addrs)} functions -> {OUT}")


if __name__ == "__main__":
    main()
