#!/usr/bin/env python3
"""Turn Ghidra's pointer targets (ghidra_scripts/ExportPointerTargets.java) into [functions]
entries for every address the recompiler did not already treat as an entry.

    tools/pointer_funcs.py logs/pointer_targets.txt > config/pointer_funcs.toml
    tools/pointer_funcs.py logs/pointer_targets.txt --prune logs/codegen.log > config/pointer_funcs.toml

--prune reads a codegen log made *with* the current config/pointer_funcs.toml. Candidates
lying between an unresolved branch and its target split a real function in two; they are
added to config/pointer_exclude.txt and left out.
Run via tools/sweep.sh, which first codegens without the sweep to learn the known entries.
"""
import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EXCLUDE_FILE = ROOT / "config/pointer_exclude.txt"


def read_known():
    known = {int(k, 16) for k in
             json.loads((ROOT / "generated/default/codegen.partition.json").read_text())["assignments"]}
    # Import thunks are not in the partition map; registering one breaks the link.
    known |= {int(a, 16) for a in re.findall(r"\{ 0x([0-9A-F]{8}), __imp__",
                                              (ROOT / "generated/default/svr2009_init.cpp").read_text())}
    return known


def read_switch_targets():
    # Case labels of jump tables analysis already resolved: data points at them, but they are
    # the middle of a function, never an entry.
    targets = set()
    for path in (ROOT / "generated/default").glob("*_recomp.*.cpp"):
        targets |= {int(a, 16) for a in re.findall(r"^\tcase [^:\n]+:\n\t\tgoto loc_([0-9A-F]{8});",
                                                   path.read_text(), re.M)}
    return targets


def read_exclude():
    if not EXCLUDE_FILE.exists():
        return set()
    return {int(l.split("#")[0], 16) for l in EXCLUDE_FILE.read_text().splitlines()
            if l.split("#")[0].strip()}


def current_entries():
    path = ROOT / "config/pointer_funcs.toml"
    return [int(l.split("=")[0], 16) for l in path.read_text().splitlines() if l.startswith("0x")]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("targets")
    ap.add_argument("--prune", metavar="CODEGEN_LOG")
    args = ap.parse_args()

    manual = {int(l.split("=")[0], 16) for l in (ROOT / "config/default.toml").read_text().splitlines()
              if l.startswith("0x")}
    exclude = read_exclude()

    if args.prune:
        entries = sorted(current_entries())
        culprits = set()
        log = Path(args.prune).read_text()
        pairs = re.findall(r"Unresolved (?:conditional branch to|function|b target) 0x([0-9A-F]+) from 0x([0-9A-F]+)",
                           log)
        for to, frm in pairs:
            lo, hi = sorted((int(to, 16), int(frm, 16)))
            culprits |= {e for e in entries if lo < e <= hi}
        new = culprits - exclude
        if new:
            with EXCLUDE_FILE.open("a") as f:
                for e in sorted(new):
                    f.write(f"0x{e:08X}  # splits a function (branch across it)\n")
        exclude |= culprits
        print(f"pruned {len(new)} entries", file=sys.stderr)
        new_entries = [e for e in entries if e not in exclude]
    else:
        known = read_known()
        cases = read_switch_targets()
        targets = [int(l, 16) for l in Path(args.targets).read_text().split()]
        new_entries = sorted(t for t in targets
                             if t not in known and t not in manual and t not in exclude and t not in cases)
        print(f"{len(targets)} candidates, {len(known)} known entries, {len(cases)} switch cases, "
              f"{len(new_entries)} new", file=sys.stderr)

    print("# Generated by tools/pointer_funcs.py: code addresses referenced from data or built with")
    print("# lis/addi (vtables, callbacks) that analysis did not register as functions.")
    print(f"# {len(new_entries)} entries.\n")
    print("[functions]")
    for t in new_entries:
        print(f"0x{t:08X} = {{}}")


if __name__ == "__main__":
    main()
