// Generated by tools/native/gen_census.py - developer call census of D3D library functions.
// Only built with -DSVR_D3D_CENSUS=ON. Do not edit by hand.

#include "generated/default/svr2009_init.h"
#include "d3d_census_runtime.h"

static constexpr uint32_t kCensusAddrs[] = {
    0x8224A828, 0x8224A9C8, 0x8224AA60, 0x8224AA88, 0x8224ABB0, 0x8224ACA8,
    0x8224AD98, 0x8224AEA8, 0x8224AF20, 0x8224AF80, 0x8224B0E8, 0x8224B180,
    0x8224B1F0, 0x8224B350, 0x8224B3F8, 0x8224B808, 0x8224B850, 0x8224B978,
    0x8224BB70, 0x8224BC00, 0x8224BC40, 0x8224BC78, 0x8224BC80, 0x8224BD20,
    0x8224BD30, 0x8224BE28, 0x8224C108, 0x8224C290, 0x8224C318, 0x8224C388,
    0x8224C390, 0x8224C3A0, 0x8224C3A8, 0x8224C440, 0x8224C458, 0x8224C460,
    0x8224C470, 0x8224C540, 0x8224C590, 0x8224C740, 0x8224C778, 0x8224C798,
    0x8224C7D8, 0x8224C858, 0x8224C870, 0x8224C920, 0x8224C9B0, 0x8224C9C0,
    0x8224C9D0, 0x8224CA08, 0x8224CA10, 0x8224CA38, 0x8224CAC8, 0x8224CB80,
    0x8224CC08, 0x8224CFB4, 0x8224CFD8, 0x8224CFF0, 0x8224D028, 0x8224D048,
    0x8224D050, 0x8224D0B8, 0x8224D110, 0x8224D434, 0x8224D900, 0x8224DC90,
    0x8224E1B0, 0x8224E270, 0x8224E2B8, 0x8224E300, 0x8224E338, 0x8224E340,
    0x8224E3F8, 0x8224E468, 0x8224E5E8, 0x8224E648, 0x8224E6D8, 0x8224E740,
    0x8224E7B0, 0x8224E848, 0x8224E858, 0x8224E938, 0x8224E9B0, 0x8224EA88,
    0x8224EAE0, 0x8224EB00, 0x8224ECC0, 0x8224EDE0, 0x8224F070, 0x8224F478,
    0x8224F5B0, 0x8224FB30, 0x8224FBD8, 0x8224FD40, 0x8224FF80, 0x822502E8,
    0x82250380, 0x8225087C, 0x82250890, 0x822510E4, 0x8225110C, 0x82251160,
    0x822513D8, 0x82251400, 0x82251450, 0x82251AFC, 0x82251C74, 0x82251C98,
    0x82251CB8, 0x82251CFC, 0x82251D24, 0x82251D30, 0x82251D48, 0x82251DA4,
    0x82251DC8, 0x82251DD0, 0x82251E60, 0x82252070, 0x82252378, 0x82252488,
    0x822524E0, 0x822525A0, 0x82252618, 0x82252698, 0x82252700, 0x822527C8,
    0x82252818, 0x82252828, 0x822528D8, 0x82252920, 0x82252930, 0x82252A88,
    0x82252E10, 0x82252F18, 0x82253178, 0x82253210, 0x822532B0, 0x822532C8,
    0x822532E0, 0x82253350, 0x822533E8, 0x82253470, 0x82253590, 0x82253900,
    0x82253A58, 0x82253E20, 0x82253F20, 0x82254020, 0x822544E8, 0x822545C0,
    0x82254650, 0x82254700, 0x82254A18, 0x82254C90, 0x82254CA0, 0x82254D58,
    0x82254D78, 0x82254E30, 0x82254E38, 0x82254EE8, 0x82254EF0, 0x82255010,
    0x82255148, 0x822551E0, 0x82255208, 0x82255250, 0x82255270, 0x822553F0,
    0x82255498, 0x82255530, 0x822555E0, 0x822556D0, 0x82255738, 0x82255790,
    0x82255828, 0x822558C8, 0x82255940, 0x82255B70, 0x82255C58, 0x82255E40,
    0x82256000, 0x822560F0, 0x822561C8, 0x82256298, 0x822564B8, 0x82256518,
    0x82256578, 0x82256678, 0x822567B0, 0x82256938, 0x82256A38, 0x82256A70,
    0x82256B00, 0x82256B68, 0x82256BE0, 0x82256C58, 0x82257098, 0x82257148,
    0x822571A4, 0x822571A8, 0x82257258, 0x82257308, 0x82257388, 0x82257400,
    0x82257458, 0x82257538, 0x82257680, 0x822576D0, 0x82257848, 0x82257878,
    0x82257940, 0x82257958, 0x82257A30, 0x82257BB8, 0x82257C08, 0x82257C60,
    0x82257CA0, 0x82257CB0, 0x82257DC0, 0x82257E18, 0x82257E68, 0x82257F40,
    0x82258230, 0x82258250, 0x82258260, 0x82258280, 0x82258290, 0x822582B8,
    0x822582C8, 0x82258348, 0x82258358, 0x822583D8, 0x822583E8, 0x82258468,
    0x82258478, 0x822584F8, 0x82258508, 0x82258568, 0x82258578, 0x822585D8,
    0x822585E8, 0x82258648, 0x82258658, 0x822586E0, 0x822586F0, 0x82258728,
    0x82258750, 0x82258770, 0x82258780, 0x82258810, 0x82258880, 0x822588A8,
    0x822588B8, 0x822588F8, 0x82258928, 0x82258948, 0x82258958, 0x82258990,
    0x82258998, 0x822589B8, 0x822589C8, 0x822589F0, 0x82258A00, 0x82258A38,
    0x82258A40, 0x82258A68, 0x82258A78, 0x82258A98, 0x82258AA8, 0x82258AD0,
    0x82258AE0, 0x82258B08, 0x82258B18, 0x82258B38, 0x82258B48, 0x82258B68,
    0x82258B78, 0x82258BA0, 0x82258BB0, 0x82258BD8, 0x82258BE8, 0x82258C08,
    0x82258C18, 0x82258C30, 0x82258C38, 0x82258C50, 0x82258C58, 0x82258C70,
    0x82258C78, 0x82258C90, 0x82258C98, 0x82258CB0, 0x82258CB8, 0x82258CD0,
    0x82258CD8, 0x82258D18, 0x82258D28, 0x82258D30, 0x82258DD8, 0x82258DF8,
    0x82258E90, 0x82258EA0, 0x82258EC0, 0x82258ED0, 0x82258EE8, 0x82258EF0,
    0x82258F28, 0x82258F30, 0x82258F68, 0x82258F70, 0x82258FA8, 0x82258FB0,
    0x82258FE8, 0x82258FF0, 0x82258FF8, 0x82259000, 0x82259048, 0x82259058,
    0x82259098, 0x822590A8, 0x822590E8, 0x822590F8, 0x82259118, 0x82259140,
    0x82259168, 0x82259190, 0x822591B8, 0x822591E0, 0x82259208, 0x82259228,
    0x82259248, 0x82259270, 0x82259298, 0x822592C0, 0x822592E8, 0x82259310,
    0x82259338, 0x82259358, 0x82259368, 0x82259378, 0x82259388, 0x82259398,
    0x822593A8, 0x822593B8, 0x822593C8, 0x822593D8, 0x822593E8, 0x822593F8,
    0x82259408, 0x82259418, 0x82259428, 0x82259438, 0x82259448, 0x82259458,
    0x82259498, 0x822594A8, 0x82259538, 0x82259540, 0x822595D0, 0x822595D8,
    0x82259668, 0x82259670, 0x82259700, 0x82259708, 0x82259730, 0x82259740,
    0x82259768, 0x82259778, 0x822597A0, 0x822597B0, 0x822597D8, 0x822597E8,
    0x82259808, 0x82259818, 0x82259838, 0x82259840, 0x82259860, 0x82259870,
    0x82259890, 0x822598A8, 0x822598D0, 0x822598D8, 0x82259900, 0x82259908,
    0x82259928, 0x82259930, 0x82259958, 0x82259960, 0x82259980, 0x82259990,
    0x822599E8, 0x822599F8, 0x82259A18, 0x82259A28, 0x82259A48, 0x82259A58,
    0x82259A78, 0x82259A88, 0x82259AA0, 0x82259AA8, 0x82259AB0, 0x82259AB8,
    0x82259AC8, 0x82259AD8, 0x82259BA0, 0x82259BD8, 0x82259C70, 0x82259C80,
    0x82259D48, 0x82259D80, 0x82259E10, 0x82259E20, 0x82259E60, 0x82259E78,
    0x82259F10, 0x82259F20, 0x82259F88, 0x82259F98, 0x82259FF8, 0x8225A040,
    0x8225A0A0, 0x8225A0E0, 0x8225A150, 0x8225A160, 0x8225A1D0, 0x8225A1E0,
    0x8225A230, 0x8225A250, 0x8225A288, 0x8225A2A0, 0x8225A2D8, 0x8225A2F0,
    0x8225A328, 0x8225A340, 0x8225A380, 0x8225A398, 0x8225A3D8, 0x8225A3F0,
    0x8225A430, 0x8225A448, 0x8225A488, 0x8225A4A0, 0x8225A4E8, 0x8225A500,
    0x8225A5F8, 0x8225A648, 0x8225A768, 0x8225A7F8, 0x8225A840, 0x8225A880,
    0x8225A8C0, 0x8225A990, 0x8225AA60, 0x8225AB58, 0x8225ADB0, 0x8225ADC0,
    0x8225AE40, 0x8225AE60, 0x8225AEF0, 0x8225B238, 0x8225B510, 0x8225B518,
    0x8225B588, 0x8225B6A0, 0x8225B850, 0x8225BA30, 0x8225BAD8, 0x8225BB58,
    0x8225BD38, 0x8225BD40, 0x8225C350, 0x8225C480, 0x8225C538, 0x8225C730,
    0x8225CAC8, 0x8225CB88, 0x8225CD08, 0x8225CE60, 0x8225CFB8, 0x8225D5C8,
    0x8225D698, 0x8225D750, 0x8225D8A0, 0x8225DA00, 0x8225DB48, 0x8225DC88,
    0x8225E518, 0x8225E688, 0x8225E698, 0x8225E6B0, 0x8225E730, 0x8225E998,
    0x8225EA90, 0x8225EE20, 0x8225EEE0, 0x8225EF28, 0x8225EF48, 0x8225EF88,
    0x8225EFB0, 0x8225F218, 0x8225F468, 0x8225F518, 0x8225F570, 0x8225F618,
    0x8225F6B0, 0x8225F728, 0x8225F940, 0x8225F990, 0x8225FA10, 0x8225FB90,
    0x822600C8, 0x822602A0, 0x822603B8, 0x82260418, 0x82260548, 0x82260558,
    0x82260638, 0x82260718, 0x82260778, 0x822607D8, 0x82260830, 0x82260888,
    0x82260A48, 0x82260A90, 0x82260B88, 0x82260D58, 0x82260DA0, 0x82260DB8,
    0x82260EA8, 0x82260F30, 0x82261018, 0x82261260, 0x822612B0, 0x82261300,
    0x822613B0, 0x82261460, 0x822615E8, 0x82261680, 0x82261708, 0x82261800,
    0x82261900, 0x8226194C, 0x82261950, 0x822619B8, 0x822619C0, 0x822619D8,
    0x82261A48, 0x82261B30, 0x82261BD0, 0x822621D8, 0x822621F0, 0x82263878,
    0x822638E8, 0x82263958, 0x822639B0, 0x82263A38, 0x82263A98, 0x82263BC0,
    0x82263BD0, 0x82263C40, 0x82263CA8, 0x82263D50, 0x82263DE8, 0x82263E40,
    0x82263EB8, 0x82263F90, 0x82264058, 0x822640C0, 0x82264118, 0x82264160,
    0x822642B8, 0x82264358, 0x82264468, 0x822648B8, 0x82264D98, 0x82264DA0,
    0x82264F78, 0x82265078, 0x82265130, 0x822651C0, 0x82265298, 0x82265338,
    0x82265AA0, 0x82265F20, 0x82266248, 0x82266938, 0x82266A68, 0x82266BE0,
    0x82266E80, 0x82266FA8, 0x82267020, 0x82267080, 0x82267120, 0x82267218,
    0x82267448, 0x822674D0, 0x82267930, 0x82267AA8, 0x82267B00, 0x82267C08,
    0x82267D10, 0x82268190, 0x82268470, 0x82268998, 0x82268B48, 0x82268BC8,
    0x82268BF8, 0x82268CE0, 0x82268CF8, 0x82268D10, 0x82268D48, 0x82268DA0,
    0x82268DE8, 0x82268E00, 0x82268E18, 0x82268E40, 0x82269100, 0x82269180,
    0x82269290, 0x82269FB0, 0x8226A068, 0x8226A490, 0x8226AD68, 0x8226AD98,
    0x8226B108, 0x8226B1F8, 0x8226B248, 0x8226B2F0, 0x8226B358, 0x8226B478,
    0x8226B8A0, 0x8226B978, 0x8226C7D0, 0x8226C848, 0x8226C900, 0x8226C968,
    0x8226CA70, 0x8226CAD0, 0x8226CC70, 0x8226CCF8, 0x8226CD98, 0x8226CE60,
    0x8226CF98, 0x8226D090, 0x8226D3D0, 0x8226D518, 0x8226D830, 0x8226D9C0,
    0x8226DB40, 0x8226DBD8, 0x8226DEC8, 0x8226E168, 0x8226E6D0, 0x8226ED80,
    0x8226EEA8, 0x8226EF68, 0x8226F138, 0x8226F200, 0x8226F268, 0x8226F2C8,
    0x8226F328, 0x8226F388, 0x8226F5E0, 0x8226F698, 0x8226F6A8, 0x8226F6B0,
    0x8226F6C0, 0x8226F6D8, 0x8226F6F0, 0x8226F708, 0x8226F718, 0x8226F728,
    0x8226F738, 0x8226F750, 0x8226F760, 0x8226F780, 0x8226F7E0, 0x8226F7F8,
    0x8226F808, 0x8226F818, 0x8226F820, 0x8226F888, 0x8226F890, 0x8226F898,
    0x8226F8A0, 0x8226F8A8, 0x8226F930, 0x8226F9A0, 0x8226FB78, 0x8226FC30,
    0x8226FC80, 0x8226FCC8, 0x8226FD20, 0x8226FD68, 0x8226FDB8, 0x8226FE20,
    0x8226FE30, 0x8226FE70, 0x8226FEB0, 0x8226FF20, 0x8226FF58, 0x8226FFC8,
    0x82270000, 0x82270010, 0x82270020, 0x822700E0, 0x822701B0, 0x82270238,
    0x822702B0, 0x82270360, 0x82270410, 0x82270490, 0x822704E0, 0x822704F8,
    0x82270570, 0x822705C8, 0x82270638, 0x82270718, 0x82270848, 0x82270928,
    0x822709C0, 0x82270A78, 0x82270C00, 0x82270C20, 0x82270C28, 0x82270C48,
    0x82270C50, 0x82270CB0, 0x82270CC8, 0x82270D38, 0x82270D48, 0x82270EE0,
    0x82270F30, 0x82270F38, 0x82270F80, 0x82271020, 0x82271098, 0x822710F8,
    0x82271150, 0x822714B8, 0x822714E0, 0x82271650, 0x822717A0, 0x822718D8,
    0x822719A0, 0x82271A30, 0x82271A4C, 0x82271A50, 0x82271B20, 0x82271BC8,
    0x82271C60, 0x82271D48, 0x82271E08, 0x82271F40, 0x82271FB8, 0x82272050,
    0x82272258, 0x82272460, 0x82272728, 0x822727B8, 0x82272890, 0x82272CD8,
    0x82272FD0, 0x82273030, 0x82273078, 0x822730C8, 0x822731E0, 0x82273230,
    0x82273520, 0x822736E8, 0x82273870, 0x82273948, 0x822739B0, 0x82273A98,
    0x82273C88, 0x82273D28, 0x82273E30, 0x82273EC0, 0x82274300, 0x822744D0,
    0x82274598, 0x822745F0, 0x82274668, 0x82274750, 0x822747A8, 0x82274908,
    0x82274A40, 0x82274AE0, 0x82274B58, 0x82274BA8, 0x82274BE0, 0x82274BF8,
    0x82274C48, 0x82274C60, 0x82274C88, 0x82274D10, 0x82274D30, 0x82274E90,
    0x82275230, 0x82275300, 0x82275308, 0x82275378, 0x822753F8, 0x82275448,
    0x82275590, 0x82275938, 0x822759B0, 0x82275A70, 0x82275E38, 0x82275ED0,
    0x82275F28, 0x82275F90, 0x82276018, 0x82276140, 0x82276188, 0x822761F0,
    0x82276260, 0x82276370, 0x822763F0, 0x82276440, 0x822764E0, 0x822764E8,
    0x82276540, 0x82276560, 0x822765A0, 0x82276678, 0x822766C8, 0x82276708,
    0x82276748, 0x822769B0, 0x82276FF8, 0x82277148, 0x82277310, 0x822774A0,
    0x82277520, 0x82277538, 0x82277670, 0x82277718, 0x82277720, 0x82277778,
    0x822777D0, 0x82277820, 0x822778A8, 0x82277930, 0x82277B70, 0x82277C98,
    0x82277E08, 0x82277FE8, 0x82278060, 0x82278240, 0x825A3AF8, 0x825A3BA0,
    0x825A3BA8, 0x825A3C48, 0x825A3CD0, 0x825A3E98, 0x825A4330, 0x825A4340,
    0x825A4790, 0x825A47D8, 0x825A4808, 0x825A4868, 0x825A4F18,
};

static svr_census::Census g_census(kCensusAddrs, 863, 469);

REX_HOOK_RAW(sub_8224A828) { g_census.Hit(0, ctx); __imp__sub_8224A828(ctx, base); }
REX_HOOK_RAW(sub_8224A9C8) { g_census.Hit(1, ctx); __imp__sub_8224A9C8(ctx, base); }
REX_HOOK_RAW(sub_8224AA60) { g_census.Hit(2, ctx); __imp__sub_8224AA60(ctx, base); }
REX_HOOK_RAW(sub_8224AA88) { g_census.Hit(3, ctx); __imp__sub_8224AA88(ctx, base); }
REX_HOOK_RAW(sub_8224ABB0) { g_census.Hit(4, ctx); __imp__sub_8224ABB0(ctx, base); }
REX_HOOK_RAW(sub_8224ACA8) { g_census.Hit(5, ctx); __imp__sub_8224ACA8(ctx, base); }
REX_HOOK_RAW(sub_8224AD98) { g_census.Hit(6, ctx); __imp__sub_8224AD98(ctx, base); }
REX_HOOK_RAW(sub_8224AEA8) { g_census.Hit(7, ctx); __imp__sub_8224AEA8(ctx, base); }
REX_HOOK_RAW(sub_8224AF20) { g_census.Hit(8, ctx); __imp__sub_8224AF20(ctx, base); }
REX_HOOK_RAW(sub_8224AF80) { g_census.Hit(9, ctx); __imp__sub_8224AF80(ctx, base); }
REX_HOOK_RAW(sub_8224B0E8) { g_census.Hit(10, ctx); __imp__sub_8224B0E8(ctx, base); }
REX_HOOK_RAW(sub_8224B180) { g_census.Hit(11, ctx); __imp__sub_8224B180(ctx, base); }
REX_HOOK_RAW(sub_8224B1F0) { g_census.Hit(12, ctx); __imp__sub_8224B1F0(ctx, base); }
REX_HOOK_RAW(sub_8224B350) { g_census.Hit(13, ctx); __imp__sub_8224B350(ctx, base); }
REX_HOOK_RAW(sub_8224B3F8) { g_census.Hit(14, ctx); __imp__sub_8224B3F8(ctx, base); }
REX_HOOK_RAW(sub_8224B808) { g_census.Hit(15, ctx); __imp__sub_8224B808(ctx, base); }
REX_HOOK_RAW(sub_8224B850) { g_census.Hit(16, ctx); __imp__sub_8224B850(ctx, base); }
REX_HOOK_RAW(sub_8224B978) { g_census.Hit(17, ctx); __imp__sub_8224B978(ctx, base); }
REX_HOOK_RAW(sub_8224BB70) { g_census.Hit(18, ctx); __imp__sub_8224BB70(ctx, base); }
REX_HOOK_RAW(sub_8224BC00) { g_census.Hit(19, ctx); __imp__sub_8224BC00(ctx, base); }
REX_HOOK_RAW(sub_8224BC40) { g_census.Hit(20, ctx); __imp__sub_8224BC40(ctx, base); }
REX_HOOK_RAW(sub_8224BC78) { g_census.Hit(21, ctx); __imp__sub_8224BC78(ctx, base); }
REX_HOOK_RAW(sub_8224BC80) { g_census.Hit(22, ctx); __imp__sub_8224BC80(ctx, base); }
REX_HOOK_RAW(sub_8224BD20) { g_census.Hit(23, ctx); __imp__sub_8224BD20(ctx, base); }
REX_HOOK_RAW(sub_8224BD30) { g_census.Hit(24, ctx); __imp__sub_8224BD30(ctx, base); }
REX_HOOK_RAW(sub_8224BE28) { g_census.Hit(25, ctx); __imp__sub_8224BE28(ctx, base); }
REX_HOOK_RAW(sub_8224C108) { g_census.Hit(26, ctx); __imp__sub_8224C108(ctx, base); }
REX_HOOK_RAW(sub_8224C290) { g_census.Hit(27, ctx); __imp__sub_8224C290(ctx, base); }
REX_HOOK_RAW(sub_8224C318) { g_census.Hit(28, ctx); __imp__sub_8224C318(ctx, base); }
REX_HOOK_RAW(sub_8224C388) { g_census.Hit(29, ctx); __imp__sub_8224C388(ctx, base); }
REX_HOOK_RAW(sub_8224C390) { g_census.Hit(30, ctx); __imp__sub_8224C390(ctx, base); }
REX_HOOK_RAW(sub_8224C3A0) { g_census.Hit(31, ctx); __imp__sub_8224C3A0(ctx, base); }
REX_HOOK_RAW(sub_8224C3A8) { g_census.Hit(32, ctx); __imp__sub_8224C3A8(ctx, base); }
REX_HOOK_RAW(sub_8224C440) { g_census.Hit(33, ctx); __imp__sub_8224C440(ctx, base); }
REX_HOOK_RAW(sub_8224C458) { g_census.Hit(34, ctx); __imp__sub_8224C458(ctx, base); }
REX_HOOK_RAW(sub_8224C460) { g_census.Hit(35, ctx); __imp__sub_8224C460(ctx, base); }
REX_HOOK_RAW(sub_8224C470) { g_census.Hit(36, ctx); __imp__sub_8224C470(ctx, base); }
REX_HOOK_RAW(sub_8224C540) { g_census.Hit(37, ctx); __imp__sub_8224C540(ctx, base); }
REX_HOOK_RAW(sub_8224C590) { g_census.Hit(38, ctx); __imp__sub_8224C590(ctx, base); }
REX_HOOK_RAW(sub_8224C740) { g_census.Hit(39, ctx); __imp__sub_8224C740(ctx, base); }
REX_HOOK_RAW(sub_8224C778) { g_census.Hit(40, ctx); __imp__sub_8224C778(ctx, base); }
REX_HOOK_RAW(sub_8224C798) { g_census.Hit(41, ctx); __imp__sub_8224C798(ctx, base); }
REX_HOOK_RAW(sub_8224C7D8) { g_census.Hit(42, ctx); __imp__sub_8224C7D8(ctx, base); }
REX_HOOK_RAW(sub_8224C858) { g_census.Hit(43, ctx); __imp__sub_8224C858(ctx, base); }
REX_HOOK_RAW(sub_8224C870) { g_census.Hit(44, ctx); __imp__sub_8224C870(ctx, base); }
REX_HOOK_RAW(sub_8224C920) { g_census.Hit(45, ctx); __imp__sub_8224C920(ctx, base); }
REX_HOOK_RAW(sub_8224C9B0) { g_census.Hit(46, ctx); __imp__sub_8224C9B0(ctx, base); }
REX_HOOK_RAW(sub_8224C9C0) { g_census.Hit(47, ctx); __imp__sub_8224C9C0(ctx, base); }
REX_HOOK_RAW(sub_8224C9D0) { g_census.Hit(48, ctx); __imp__sub_8224C9D0(ctx, base); }
REX_HOOK_RAW(sub_8224CA08) { g_census.Hit(49, ctx); __imp__sub_8224CA08(ctx, base); }
REX_HOOK_RAW(sub_8224CA10) { g_census.Hit(50, ctx); __imp__sub_8224CA10(ctx, base); }
REX_HOOK_RAW(sub_8224CA38) { g_census.Hit(51, ctx); __imp__sub_8224CA38(ctx, base); }
REX_HOOK_RAW(sub_8224CAC8) { g_census.Hit(52, ctx); __imp__sub_8224CAC8(ctx, base); }
REX_HOOK_RAW(sub_8224CB80) { g_census.Hit(53, ctx); __imp__sub_8224CB80(ctx, base); }
REX_HOOK_RAW(sub_8224CC08) { g_census.Hit(54, ctx); __imp__sub_8224CC08(ctx, base); }
REX_HOOK_RAW(sub_8224CFB4) { g_census.Hit(55, ctx); __imp__sub_8224CFB4(ctx, base); }
REX_HOOK_RAW(sub_8224CFD8) { g_census.Hit(56, ctx); __imp__sub_8224CFD8(ctx, base); }
REX_HOOK_RAW(sub_8224CFF0) { g_census.Hit(57, ctx); __imp__sub_8224CFF0(ctx, base); }
REX_HOOK_RAW(sub_8224D028) { g_census.Hit(58, ctx); __imp__sub_8224D028(ctx, base); }
REX_HOOK_RAW(sub_8224D048) { g_census.Hit(59, ctx); __imp__sub_8224D048(ctx, base); }
REX_HOOK_RAW(sub_8224D050) { g_census.Hit(60, ctx); __imp__sub_8224D050(ctx, base); }
REX_HOOK_RAW(sub_8224D0B8) { g_census.Hit(61, ctx); __imp__sub_8224D0B8(ctx, base); }
REX_HOOK_RAW(sub_8224D110) { g_census.Hit(62, ctx); __imp__sub_8224D110(ctx, base); }
REX_HOOK_RAW(sub_8224D434) { g_census.Hit(63, ctx); __imp__sub_8224D434(ctx, base); }
REX_HOOK_RAW(sub_8224D900) { g_census.Hit(64, ctx); __imp__sub_8224D900(ctx, base); }
REX_HOOK_RAW(sub_8224DC90) { g_census.Hit(65, ctx); __imp__sub_8224DC90(ctx, base); }
REX_HOOK_RAW(sub_8224E1B0) { g_census.Hit(66, ctx); __imp__sub_8224E1B0(ctx, base); }
REX_HOOK_RAW(sub_8224E270) { g_census.Hit(67, ctx); __imp__sub_8224E270(ctx, base); }
REX_HOOK_RAW(sub_8224E2B8) { g_census.Hit(68, ctx); __imp__sub_8224E2B8(ctx, base); }
REX_HOOK_RAW(sub_8224E300) { g_census.Hit(69, ctx); __imp__sub_8224E300(ctx, base); }
REX_HOOK_RAW(sub_8224E338) { g_census.Hit(70, ctx); __imp__sub_8224E338(ctx, base); }
REX_HOOK_RAW(sub_8224E340) { g_census.Hit(71, ctx); __imp__sub_8224E340(ctx, base); }
REX_HOOK_RAW(sub_8224E3F8) { g_census.Hit(72, ctx); __imp__sub_8224E3F8(ctx, base); }
REX_HOOK_RAW(sub_8224E468) { g_census.Hit(73, ctx); __imp__sub_8224E468(ctx, base); }
REX_HOOK_RAW(sub_8224E5E8) { g_census.Hit(74, ctx); __imp__sub_8224E5E8(ctx, base); }
REX_HOOK_RAW(sub_8224E648) { g_census.Hit(75, ctx); __imp__sub_8224E648(ctx, base); }
REX_HOOK_RAW(sub_8224E6D8) { g_census.Hit(76, ctx); __imp__sub_8224E6D8(ctx, base); }
REX_HOOK_RAW(sub_8224E740) { g_census.Hit(77, ctx); __imp__sub_8224E740(ctx, base); }
REX_HOOK_RAW(sub_8224E7B0) { g_census.Hit(78, ctx); __imp__sub_8224E7B0(ctx, base); }
REX_HOOK_RAW(sub_8224E848) { g_census.Hit(79, ctx); __imp__sub_8224E848(ctx, base); }
REX_HOOK_RAW(sub_8224E858) { g_census.Hit(80, ctx); __imp__sub_8224E858(ctx, base); }
REX_HOOK_RAW(sub_8224E938) { g_census.Hit(81, ctx); __imp__sub_8224E938(ctx, base); }
REX_HOOK_RAW(sub_8224E9B0) { g_census.Hit(82, ctx); __imp__sub_8224E9B0(ctx, base); }
REX_HOOK_RAW(sub_8224EA88) { g_census.Hit(83, ctx); __imp__sub_8224EA88(ctx, base); }
REX_HOOK_RAW(sub_8224EAE0) { g_census.Hit(84, ctx); __imp__sub_8224EAE0(ctx, base); }
REX_HOOK_RAW(sub_8224EB00) { g_census.Hit(85, ctx); __imp__sub_8224EB00(ctx, base); }
REX_HOOK_RAW(sub_8224ECC0) { g_census.Hit(86, ctx); __imp__sub_8224ECC0(ctx, base); }
REX_HOOK_RAW(sub_8224EDE0) { g_census.Hit(87, ctx); __imp__sub_8224EDE0(ctx, base); }
REX_HOOK_RAW(sub_8224F070) { g_census.Hit(88, ctx); __imp__sub_8224F070(ctx, base); }
REX_HOOK_RAW(sub_8224F478) { g_census.Hit(89, ctx); __imp__sub_8224F478(ctx, base); }
REX_HOOK_RAW(sub_8224F5B0) { g_census.Hit(90, ctx); __imp__sub_8224F5B0(ctx, base); }
REX_HOOK_RAW(sub_8224FB30) { g_census.Hit(91, ctx); __imp__sub_8224FB30(ctx, base); }
REX_HOOK_RAW(sub_8224FBD8) { g_census.Hit(92, ctx); __imp__sub_8224FBD8(ctx, base); }
REX_HOOK_RAW(sub_8224FD40) { g_census.Hit(93, ctx); __imp__sub_8224FD40(ctx, base); }
REX_HOOK_RAW(sub_8224FF80) { g_census.Hit(94, ctx); __imp__sub_8224FF80(ctx, base); }
REX_HOOK_RAW(sub_822502E8) { g_census.Hit(95, ctx); __imp__sub_822502E8(ctx, base); }
REX_HOOK_RAW(sub_82250380) { g_census.Hit(96, ctx); __imp__sub_82250380(ctx, base); }
REX_HOOK_RAW(sub_8225087C) { g_census.Hit(97, ctx); __imp__sub_8225087C(ctx, base); }
REX_HOOK_RAW(sub_82250890) { g_census.Hit(98, ctx); __imp__sub_82250890(ctx, base); }
REX_HOOK_RAW(sub_822510E4) { g_census.Hit(99, ctx); __imp__sub_822510E4(ctx, base); }
REX_HOOK_RAW(sub_8225110C) { g_census.Hit(100, ctx); __imp__sub_8225110C(ctx, base); }
REX_HOOK_RAW(sub_82251160) { g_census.Hit(101, ctx); __imp__sub_82251160(ctx, base); }
REX_HOOK_RAW(sub_822513D8) { g_census.Hit(102, ctx); __imp__sub_822513D8(ctx, base); }
REX_HOOK_RAW(sub_82251400) { g_census.Hit(103, ctx); __imp__sub_82251400(ctx, base); }
REX_HOOK_RAW(sub_82251450) { g_census.Hit(104, ctx); __imp__sub_82251450(ctx, base); }
REX_HOOK_RAW(sub_82251AFC) { g_census.Hit(105, ctx); __imp__sub_82251AFC(ctx, base); }
REX_HOOK_RAW(sub_82251C74) { g_census.Hit(106, ctx); __imp__sub_82251C74(ctx, base); }
REX_HOOK_RAW(sub_82251C98) { g_census.Hit(107, ctx); __imp__sub_82251C98(ctx, base); }
REX_HOOK_RAW(sub_82251CB8) { g_census.Hit(108, ctx); __imp__sub_82251CB8(ctx, base); }
REX_HOOK_RAW(sub_82251CFC) { g_census.Hit(109, ctx); __imp__sub_82251CFC(ctx, base); }
REX_HOOK_RAW(sub_82251D24) { g_census.Hit(110, ctx); __imp__sub_82251D24(ctx, base); }
REX_HOOK_RAW(sub_82251D30) { g_census.Hit(111, ctx); __imp__sub_82251D30(ctx, base); }
REX_HOOK_RAW(sub_82251D48) { g_census.Hit(112, ctx); __imp__sub_82251D48(ctx, base); }
REX_HOOK_RAW(sub_82251DA4) { g_census.Hit(113, ctx); __imp__sub_82251DA4(ctx, base); }
REX_HOOK_RAW(sub_82251DC8) { g_census.Hit(114, ctx); __imp__sub_82251DC8(ctx, base); }
REX_HOOK_RAW(sub_82251DD0) { g_census.Hit(115, ctx); __imp__sub_82251DD0(ctx, base); }
REX_HOOK_RAW(sub_82251E60) { g_census.Hit(116, ctx); __imp__sub_82251E60(ctx, base); }
REX_HOOK_RAW(sub_82252070) { g_census.Hit(117, ctx); __imp__sub_82252070(ctx, base); }
REX_HOOK_RAW(sub_82252378) { g_census.Hit(118, ctx); __imp__sub_82252378(ctx, base); }
REX_HOOK_RAW(sub_82252488) { g_census.Hit(119, ctx); __imp__sub_82252488(ctx, base); }
REX_HOOK_RAW(sub_822524E0) { g_census.Hit(120, ctx); __imp__sub_822524E0(ctx, base); }
REX_HOOK_RAW(sub_822525A0) { g_census.Hit(121, ctx); __imp__sub_822525A0(ctx, base); }
REX_HOOK_RAW(sub_82252618) { g_census.Hit(122, ctx); __imp__sub_82252618(ctx, base); }
REX_HOOK_RAW(sub_82252698) { g_census.Hit(123, ctx); __imp__sub_82252698(ctx, base); }
REX_HOOK_RAW(sub_82252700) { g_census.Hit(124, ctx); __imp__sub_82252700(ctx, base); }
REX_HOOK_RAW(sub_822527C8) { g_census.Hit(125, ctx); __imp__sub_822527C8(ctx, base); }
REX_HOOK_RAW(sub_82252818) { g_census.Hit(126, ctx); __imp__sub_82252818(ctx, base); }
REX_HOOK_RAW(sub_82252828) { g_census.Hit(127, ctx); __imp__sub_82252828(ctx, base); }
REX_HOOK_RAW(sub_822528D8) { g_census.Hit(128, ctx); __imp__sub_822528D8(ctx, base); }
REX_HOOK_RAW(sub_82252920) { g_census.Hit(129, ctx); __imp__sub_82252920(ctx, base); }
REX_HOOK_RAW(sub_82252930) { g_census.Hit(130, ctx); __imp__sub_82252930(ctx, base); }
REX_HOOK_RAW(sub_82252A88) { g_census.Hit(131, ctx); __imp__sub_82252A88(ctx, base); }
REX_HOOK_RAW(sub_82252E10) { g_census.Hit(132, ctx); __imp__sub_82252E10(ctx, base); }
REX_HOOK_RAW(sub_82252F18) { g_census.Hit(133, ctx); __imp__sub_82252F18(ctx, base); }
REX_HOOK_RAW(sub_82253178) { g_census.Hit(134, ctx); __imp__sub_82253178(ctx, base); }
REX_HOOK_RAW(sub_82253210) { g_census.Hit(135, ctx); __imp__sub_82253210(ctx, base); }
REX_HOOK_RAW(sub_822532B0) { g_census.Hit(136, ctx); __imp__sub_822532B0(ctx, base); }
REX_HOOK_RAW(sub_822532C8) { g_census.Hit(137, ctx); __imp__sub_822532C8(ctx, base); }
REX_HOOK_RAW(sub_822532E0) { g_census.Hit(138, ctx); __imp__sub_822532E0(ctx, base); }
REX_HOOK_RAW(sub_82253350) { g_census.Hit(139, ctx); __imp__sub_82253350(ctx, base); }
REX_HOOK_RAW(sub_822533E8) { g_census.Hit(140, ctx); __imp__sub_822533E8(ctx, base); }
REX_HOOK_RAW(sub_82253470) { g_census.Hit(141, ctx); __imp__sub_82253470(ctx, base); }
REX_HOOK_RAW(sub_82253590) { g_census.Hit(142, ctx); __imp__sub_82253590(ctx, base); }
REX_HOOK_RAW(sub_82253900) { g_census.Hit(143, ctx); __imp__sub_82253900(ctx, base); }
REX_HOOK_RAW(sub_82253A58) { g_census.Hit(144, ctx); __imp__sub_82253A58(ctx, base); }
REX_HOOK_RAW(sub_82253E20) { g_census.Hit(145, ctx); __imp__sub_82253E20(ctx, base); }
REX_HOOK_RAW(sub_82253F20) { g_census.Hit(146, ctx); __imp__sub_82253F20(ctx, base); }
REX_HOOK_RAW(sub_82254020) { g_census.Hit(147, ctx); __imp__sub_82254020(ctx, base); }
REX_HOOK_RAW(sub_822544E8) { g_census.Hit(148, ctx); __imp__sub_822544E8(ctx, base); }
REX_HOOK_RAW(sub_822545C0) { g_census.Hit(149, ctx); __imp__sub_822545C0(ctx, base); }
REX_HOOK_RAW(sub_82254650) { g_census.Hit(150, ctx); __imp__sub_82254650(ctx, base); }
REX_HOOK_RAW(sub_82254700) { g_census.Hit(151, ctx); __imp__sub_82254700(ctx, base); }
REX_HOOK_RAW(sub_82254A18) { g_census.Hit(152, ctx); __imp__sub_82254A18(ctx, base); }
REX_HOOK_RAW(sub_82254C90) { g_census.Hit(153, ctx); __imp__sub_82254C90(ctx, base); }
REX_HOOK_RAW(sub_82254CA0) { g_census.Hit(154, ctx); __imp__sub_82254CA0(ctx, base); }
REX_HOOK_RAW(sub_82254D58) { g_census.Hit(155, ctx); __imp__sub_82254D58(ctx, base); }
REX_HOOK_RAW(sub_82254D78) { g_census.Hit(156, ctx); __imp__sub_82254D78(ctx, base); }
REX_HOOK_RAW(sub_82254E30) { g_census.Hit(157, ctx); __imp__sub_82254E30(ctx, base); }
REX_HOOK_RAW(sub_82254E38) { g_census.Hit(158, ctx); __imp__sub_82254E38(ctx, base); }
REX_HOOK_RAW(sub_82254EE8) { g_census.Hit(159, ctx); __imp__sub_82254EE8(ctx, base); }
REX_HOOK_RAW(sub_82254EF0) { g_census.Hit(160, ctx); __imp__sub_82254EF0(ctx, base); }
REX_HOOK_RAW(sub_82255010) { g_census.Hit(161, ctx); __imp__sub_82255010(ctx, base); }
REX_HOOK_RAW(sub_82255148) { g_census.Hit(162, ctx); __imp__sub_82255148(ctx, base); }
REX_HOOK_RAW(sub_822551E0) { g_census.Hit(163, ctx); __imp__sub_822551E0(ctx, base); }
REX_HOOK_RAW(sub_82255208) { g_census.Hit(164, ctx); __imp__sub_82255208(ctx, base); }
REX_HOOK_RAW(sub_82255250) { g_census.Hit(165, ctx); __imp__sub_82255250(ctx, base); }
REX_HOOK_RAW(sub_82255270) { g_census.Hit(166, ctx); __imp__sub_82255270(ctx, base); }
REX_HOOK_RAW(sub_822553F0) { g_census.Hit(167, ctx); __imp__sub_822553F0(ctx, base); }
REX_HOOK_RAW(sub_82255498) { g_census.Hit(168, ctx); __imp__sub_82255498(ctx, base); }
REX_HOOK_RAW(sub_82255530) { g_census.Hit(169, ctx); __imp__sub_82255530(ctx, base); }
REX_HOOK_RAW(sub_822555E0) { g_census.Hit(170, ctx); __imp__sub_822555E0(ctx, base); }
REX_HOOK_RAW(sub_822556D0) { g_census.Hit(171, ctx); __imp__sub_822556D0(ctx, base); }
REX_HOOK_RAW(sub_82255738) { g_census.Hit(172, ctx); __imp__sub_82255738(ctx, base); }
REX_HOOK_RAW(sub_82255790) { g_census.Hit(173, ctx); __imp__sub_82255790(ctx, base); }
REX_HOOK_RAW(sub_82255828) { g_census.Hit(174, ctx); __imp__sub_82255828(ctx, base); }
REX_HOOK_RAW(sub_822558C8) { g_census.Hit(175, ctx); __imp__sub_822558C8(ctx, base); }
REX_HOOK_RAW(sub_82255940) { g_census.Hit(176, ctx); __imp__sub_82255940(ctx, base); }
REX_HOOK_RAW(sub_82255B70) { g_census.Hit(177, ctx); __imp__sub_82255B70(ctx, base); }
REX_HOOK_RAW(sub_82255C58) { g_census.Hit(178, ctx); __imp__sub_82255C58(ctx, base); }
REX_HOOK_RAW(sub_82255E40) { g_census.Hit(179, ctx); __imp__sub_82255E40(ctx, base); }
REX_HOOK_RAW(sub_82256000) { g_census.Hit(180, ctx); __imp__sub_82256000(ctx, base); }
REX_HOOK_RAW(sub_822560F0) { g_census.Hit(181, ctx); __imp__sub_822560F0(ctx, base); }
REX_HOOK_RAW(sub_822561C8) { g_census.Hit(182, ctx); __imp__sub_822561C8(ctx, base); }
REX_HOOK_RAW(sub_82256298) { g_census.Hit(183, ctx); __imp__sub_82256298(ctx, base); }
REX_HOOK_RAW(sub_822564B8) { g_census.Hit(184, ctx); __imp__sub_822564B8(ctx, base); }
REX_HOOK_RAW(sub_82256518) { g_census.Hit(185, ctx); __imp__sub_82256518(ctx, base); }
REX_HOOK_RAW(sub_82256578) { g_census.Hit(186, ctx); __imp__sub_82256578(ctx, base); }
REX_HOOK_RAW(sub_82256678) { g_census.Hit(187, ctx); __imp__sub_82256678(ctx, base); }
REX_HOOK_RAW(sub_822567B0) { g_census.Hit(188, ctx); __imp__sub_822567B0(ctx, base); }
REX_HOOK_RAW(sub_82256938) { g_census.Hit(189, ctx); __imp__sub_82256938(ctx, base); }
REX_HOOK_RAW(sub_82256A38) { g_census.Hit(190, ctx); __imp__sub_82256A38(ctx, base); }
REX_HOOK_RAW(sub_82256A70) { g_census.Hit(191, ctx); __imp__sub_82256A70(ctx, base); }
REX_HOOK_RAW(sub_82256B00) { g_census.Hit(192, ctx); __imp__sub_82256B00(ctx, base); }
REX_HOOK_RAW(sub_82256B68) { g_census.Hit(193, ctx); __imp__sub_82256B68(ctx, base); }
REX_HOOK_RAW(sub_82256BE0) { g_census.Hit(194, ctx); __imp__sub_82256BE0(ctx, base); }
REX_HOOK_RAW(sub_82256C58) { g_census.Hit(195, ctx); __imp__sub_82256C58(ctx, base); }
REX_HOOK_RAW(sub_82257098) { g_census.Hit(196, ctx); __imp__sub_82257098(ctx, base); }
REX_HOOK_RAW(sub_82257148) { g_census.Hit(197, ctx); __imp__sub_82257148(ctx, base); }
REX_HOOK_RAW(sub_822571A4) { g_census.Hit(198, ctx); __imp__sub_822571A4(ctx, base); }
REX_HOOK_RAW(sub_822571A8) { g_census.Hit(199, ctx); __imp__sub_822571A8(ctx, base); }
REX_HOOK_RAW(sub_82257258) { g_census.Hit(200, ctx); __imp__sub_82257258(ctx, base); }
REX_HOOK_RAW(sub_82257308) { g_census.Hit(201, ctx); __imp__sub_82257308(ctx, base); }
REX_HOOK_RAW(sub_82257388) { g_census.Hit(202, ctx); __imp__sub_82257388(ctx, base); }
REX_HOOK_RAW(sub_82257400) { g_census.Hit(203, ctx); __imp__sub_82257400(ctx, base); }
REX_HOOK_RAW(sub_82257458) { g_census.Hit(204, ctx); __imp__sub_82257458(ctx, base); }
REX_HOOK_RAW(sub_82257538) { g_census.Hit(205, ctx); __imp__sub_82257538(ctx, base); }
REX_HOOK_RAW(sub_82257680) { g_census.Hit(206, ctx); __imp__sub_82257680(ctx, base); }
REX_HOOK_RAW(sub_822576D0) { g_census.Hit(207, ctx); __imp__sub_822576D0(ctx, base); }
REX_HOOK_RAW(sub_82257848) { g_census.Hit(208, ctx); __imp__sub_82257848(ctx, base); }
REX_HOOK_RAW(sub_82257878) { g_census.Hit(209, ctx); __imp__sub_82257878(ctx, base); }
REX_HOOK_RAW(sub_82257940) { g_census.Hit(210, ctx); __imp__sub_82257940(ctx, base); }
REX_HOOK_RAW(sub_82257958) { g_census.Hit(211, ctx); __imp__sub_82257958(ctx, base); }
REX_HOOK_RAW(sub_82257A30) { g_census.Hit(212, ctx); __imp__sub_82257A30(ctx, base); }
REX_HOOK_RAW(sub_82257BB8) { g_census.Hit(213, ctx); __imp__sub_82257BB8(ctx, base); }
REX_HOOK_RAW(sub_82257C08) { g_census.Hit(214, ctx); __imp__sub_82257C08(ctx, base); }
REX_HOOK_RAW(sub_82257C60) { g_census.Hit(215, ctx); __imp__sub_82257C60(ctx, base); }
REX_HOOK_RAW(sub_82257CA0) { g_census.Hit(216, ctx); __imp__sub_82257CA0(ctx, base); }
REX_HOOK_RAW(sub_82257CB0) { g_census.Hit(217, ctx); __imp__sub_82257CB0(ctx, base); }
REX_HOOK_RAW(sub_82257DC0) { g_census.Hit(218, ctx); __imp__sub_82257DC0(ctx, base); }
REX_HOOK_RAW(sub_82257E18) { g_census.Hit(219, ctx); __imp__sub_82257E18(ctx, base); }
REX_HOOK_RAW(sub_82257E68) { g_census.Hit(220, ctx); __imp__sub_82257E68(ctx, base); }
REX_HOOK_RAW(sub_82257F40) { g_census.Hit(221, ctx); __imp__sub_82257F40(ctx, base); }
REX_HOOK_RAW(sub_82258230) { g_census.Hit(222, ctx); __imp__sub_82258230(ctx, base); }
REX_HOOK_RAW(sub_82258250) { g_census.Hit(223, ctx); __imp__sub_82258250(ctx, base); }
REX_HOOK_RAW(sub_82258260) { g_census.Hit(224, ctx); __imp__sub_82258260(ctx, base); }
REX_HOOK_RAW(sub_82258280) { g_census.Hit(225, ctx); __imp__sub_82258280(ctx, base); }
REX_HOOK_RAW(sub_82258290) { g_census.Hit(226, ctx); __imp__sub_82258290(ctx, base); }
REX_HOOK_RAW(sub_822582B8) { g_census.Hit(227, ctx); __imp__sub_822582B8(ctx, base); }
REX_HOOK_RAW(sub_822582C8) { g_census.Hit(228, ctx); __imp__sub_822582C8(ctx, base); }
REX_HOOK_RAW(sub_82258348) { g_census.Hit(229, ctx); __imp__sub_82258348(ctx, base); }
REX_HOOK_RAW(sub_82258358) { g_census.Hit(230, ctx); __imp__sub_82258358(ctx, base); }
REX_HOOK_RAW(sub_822583D8) { g_census.Hit(231, ctx); __imp__sub_822583D8(ctx, base); }
REX_HOOK_RAW(sub_822583E8) { g_census.Hit(232, ctx); __imp__sub_822583E8(ctx, base); }
REX_HOOK_RAW(sub_82258468) { g_census.Hit(233, ctx); __imp__sub_82258468(ctx, base); }
REX_HOOK_RAW(sub_82258478) { g_census.Hit(234, ctx); __imp__sub_82258478(ctx, base); }
REX_HOOK_RAW(sub_822584F8) { g_census.Hit(235, ctx); __imp__sub_822584F8(ctx, base); }
REX_HOOK_RAW(sub_82258508) { g_census.Hit(236, ctx); __imp__sub_82258508(ctx, base); }
REX_HOOK_RAW(sub_82258568) { g_census.Hit(237, ctx); __imp__sub_82258568(ctx, base); }
REX_HOOK_RAW(sub_82258578) { g_census.Hit(238, ctx); __imp__sub_82258578(ctx, base); }
REX_HOOK_RAW(sub_822585D8) { g_census.Hit(239, ctx); __imp__sub_822585D8(ctx, base); }
REX_HOOK_RAW(sub_822585E8) { g_census.Hit(240, ctx); __imp__sub_822585E8(ctx, base); }
REX_HOOK_RAW(sub_82258648) { g_census.Hit(241, ctx); __imp__sub_82258648(ctx, base); }
REX_HOOK_RAW(sub_82258658) { g_census.Hit(242, ctx); __imp__sub_82258658(ctx, base); }
REX_HOOK_RAW(sub_822586E0) { g_census.Hit(243, ctx); __imp__sub_822586E0(ctx, base); }
REX_HOOK_RAW(sub_822586F0) { g_census.Hit(244, ctx); __imp__sub_822586F0(ctx, base); }
REX_HOOK_RAW(sub_82258728) { g_census.Hit(245, ctx); __imp__sub_82258728(ctx, base); }
REX_HOOK_RAW(sub_82258750) { g_census.Hit(246, ctx); __imp__sub_82258750(ctx, base); }
REX_HOOK_RAW(sub_82258770) { g_census.Hit(247, ctx); __imp__sub_82258770(ctx, base); }
REX_HOOK_RAW(sub_82258780) { g_census.Hit(248, ctx); __imp__sub_82258780(ctx, base); }
REX_HOOK_RAW(sub_82258810) { g_census.Hit(249, ctx); __imp__sub_82258810(ctx, base); }
REX_HOOK_RAW(sub_82258880) { g_census.Hit(250, ctx); __imp__sub_82258880(ctx, base); }
REX_HOOK_RAW(sub_822588A8) { g_census.Hit(251, ctx); __imp__sub_822588A8(ctx, base); }
REX_HOOK_RAW(sub_822588B8) { g_census.Hit(252, ctx); __imp__sub_822588B8(ctx, base); }
REX_HOOK_RAW(sub_822588F8) { g_census.Hit(253, ctx); __imp__sub_822588F8(ctx, base); }
REX_HOOK_RAW(sub_82258928) { g_census.Hit(254, ctx); __imp__sub_82258928(ctx, base); }
REX_HOOK_RAW(sub_82258948) { g_census.Hit(255, ctx); __imp__sub_82258948(ctx, base); }
REX_HOOK_RAW(sub_82258958) { g_census.Hit(256, ctx); __imp__sub_82258958(ctx, base); }
REX_HOOK_RAW(sub_82258990) { g_census.Hit(257, ctx); __imp__sub_82258990(ctx, base); }
REX_HOOK_RAW(sub_82258998) { g_census.Hit(258, ctx); __imp__sub_82258998(ctx, base); }
REX_HOOK_RAW(sub_822589B8) { g_census.Hit(259, ctx); __imp__sub_822589B8(ctx, base); }
REX_HOOK_RAW(sub_822589C8) { g_census.Hit(260, ctx); __imp__sub_822589C8(ctx, base); }
REX_HOOK_RAW(sub_822589F0) { g_census.Hit(261, ctx); __imp__sub_822589F0(ctx, base); }
REX_HOOK_RAW(sub_82258A00) { g_census.Hit(262, ctx); __imp__sub_82258A00(ctx, base); }
REX_HOOK_RAW(sub_82258A38) { g_census.Hit(263, ctx); __imp__sub_82258A38(ctx, base); }
REX_HOOK_RAW(sub_82258A40) { g_census.Hit(264, ctx); __imp__sub_82258A40(ctx, base); }
REX_HOOK_RAW(sub_82258A68) { g_census.Hit(265, ctx); __imp__sub_82258A68(ctx, base); }
REX_HOOK_RAW(sub_82258A78) { g_census.Hit(266, ctx); __imp__sub_82258A78(ctx, base); }
REX_HOOK_RAW(sub_82258A98) { g_census.Hit(267, ctx); __imp__sub_82258A98(ctx, base); }
REX_HOOK_RAW(sub_82258AA8) { g_census.Hit(268, ctx); __imp__sub_82258AA8(ctx, base); }
REX_HOOK_RAW(sub_82258AD0) { g_census.Hit(269, ctx); __imp__sub_82258AD0(ctx, base); }
REX_HOOK_RAW(sub_82258AE0) { g_census.Hit(270, ctx); __imp__sub_82258AE0(ctx, base); }
REX_HOOK_RAW(sub_82258B08) { g_census.Hit(271, ctx); __imp__sub_82258B08(ctx, base); }
REX_HOOK_RAW(sub_82258B18) { g_census.Hit(272, ctx); __imp__sub_82258B18(ctx, base); }
REX_HOOK_RAW(sub_82258B38) { g_census.Hit(273, ctx); __imp__sub_82258B38(ctx, base); }
REX_HOOK_RAW(sub_82258B48) { g_census.Hit(274, ctx); __imp__sub_82258B48(ctx, base); }
REX_HOOK_RAW(sub_82258B68) { g_census.Hit(275, ctx); __imp__sub_82258B68(ctx, base); }
REX_HOOK_RAW(sub_82258B78) { g_census.Hit(276, ctx); __imp__sub_82258B78(ctx, base); }
REX_HOOK_RAW(sub_82258BA0) { g_census.Hit(277, ctx); __imp__sub_82258BA0(ctx, base); }
REX_HOOK_RAW(sub_82258BB0) { g_census.Hit(278, ctx); __imp__sub_82258BB0(ctx, base); }
REX_HOOK_RAW(sub_82258BD8) { g_census.Hit(279, ctx); __imp__sub_82258BD8(ctx, base); }
REX_HOOK_RAW(sub_82258BE8) { g_census.Hit(280, ctx); __imp__sub_82258BE8(ctx, base); }
REX_HOOK_RAW(sub_82258C08) { g_census.Hit(281, ctx); __imp__sub_82258C08(ctx, base); }
REX_HOOK_RAW(sub_82258C18) { g_census.Hit(282, ctx); __imp__sub_82258C18(ctx, base); }
REX_HOOK_RAW(sub_82258C30) { g_census.Hit(283, ctx); __imp__sub_82258C30(ctx, base); }
REX_HOOK_RAW(sub_82258C38) { g_census.Hit(284, ctx); __imp__sub_82258C38(ctx, base); }
REX_HOOK_RAW(sub_82258C50) { g_census.Hit(285, ctx); __imp__sub_82258C50(ctx, base); }
REX_HOOK_RAW(sub_82258C58) { g_census.Hit(286, ctx); __imp__sub_82258C58(ctx, base); }
REX_HOOK_RAW(sub_82258C70) { g_census.Hit(287, ctx); __imp__sub_82258C70(ctx, base); }
REX_HOOK_RAW(sub_82258C78) { g_census.Hit(288, ctx); __imp__sub_82258C78(ctx, base); }
REX_HOOK_RAW(sub_82258C90) { g_census.Hit(289, ctx); __imp__sub_82258C90(ctx, base); }
REX_HOOK_RAW(sub_82258C98) { g_census.Hit(290, ctx); __imp__sub_82258C98(ctx, base); }
REX_HOOK_RAW(sub_82258CB0) { g_census.Hit(291, ctx); __imp__sub_82258CB0(ctx, base); }
REX_HOOK_RAW(sub_82258CB8) { g_census.Hit(292, ctx); __imp__sub_82258CB8(ctx, base); }
REX_HOOK_RAW(sub_82258CD0) { g_census.Hit(293, ctx); __imp__sub_82258CD0(ctx, base); }
REX_HOOK_RAW(sub_82258CD8) { g_census.Hit(294, ctx); __imp__sub_82258CD8(ctx, base); }
REX_HOOK_RAW(sub_82258D18) { g_census.Hit(295, ctx); __imp__sub_82258D18(ctx, base); }
REX_HOOK_RAW(sub_82258D28) { g_census.Hit(296, ctx); __imp__sub_82258D28(ctx, base); }
REX_HOOK_RAW(sub_82258D30) { g_census.Hit(297, ctx); __imp__sub_82258D30(ctx, base); }
REX_HOOK_RAW(sub_82258DD8) { g_census.Hit(298, ctx); __imp__sub_82258DD8(ctx, base); }
REX_HOOK_RAW(sub_82258DF8) { g_census.Hit(299, ctx); __imp__sub_82258DF8(ctx, base); }
REX_HOOK_RAW(sub_82258E90) { g_census.Hit(300, ctx); __imp__sub_82258E90(ctx, base); }
REX_HOOK_RAW(sub_82258EA0) { g_census.Hit(301, ctx); __imp__sub_82258EA0(ctx, base); }
REX_HOOK_RAW(sub_82258EC0) { g_census.Hit(302, ctx); __imp__sub_82258EC0(ctx, base); }
REX_HOOK_RAW(sub_82258ED0) { g_census.Hit(303, ctx); __imp__sub_82258ED0(ctx, base); }
REX_HOOK_RAW(sub_82258EE8) { g_census.Hit(304, ctx); __imp__sub_82258EE8(ctx, base); }
REX_HOOK_RAW(sub_82258EF0) { g_census.Hit(305, ctx); __imp__sub_82258EF0(ctx, base); }
REX_HOOK_RAW(sub_82258F28) { g_census.Hit(306, ctx); __imp__sub_82258F28(ctx, base); }
REX_HOOK_RAW(sub_82258F30) { g_census.Hit(307, ctx); __imp__sub_82258F30(ctx, base); }
REX_HOOK_RAW(sub_82258F68) { g_census.Hit(308, ctx); __imp__sub_82258F68(ctx, base); }
REX_HOOK_RAW(sub_82258F70) { g_census.Hit(309, ctx); __imp__sub_82258F70(ctx, base); }
REX_HOOK_RAW(sub_82258FA8) { g_census.Hit(310, ctx); __imp__sub_82258FA8(ctx, base); }
REX_HOOK_RAW(sub_82258FB0) { g_census.Hit(311, ctx); __imp__sub_82258FB0(ctx, base); }
REX_HOOK_RAW(sub_82258FE8) { g_census.Hit(312, ctx); __imp__sub_82258FE8(ctx, base); }
REX_HOOK_RAW(sub_82258FF0) { g_census.Hit(313, ctx); __imp__sub_82258FF0(ctx, base); }
REX_HOOK_RAW(sub_82258FF8) { g_census.Hit(314, ctx); __imp__sub_82258FF8(ctx, base); }
REX_HOOK_RAW(sub_82259000) { g_census.Hit(315, ctx); __imp__sub_82259000(ctx, base); }
REX_HOOK_RAW(sub_82259048) { g_census.Hit(316, ctx); __imp__sub_82259048(ctx, base); }
REX_HOOK_RAW(sub_82259058) { g_census.Hit(317, ctx); __imp__sub_82259058(ctx, base); }
REX_HOOK_RAW(sub_82259098) { g_census.Hit(318, ctx); __imp__sub_82259098(ctx, base); }
REX_HOOK_RAW(sub_822590A8) { g_census.Hit(319, ctx); __imp__sub_822590A8(ctx, base); }
REX_HOOK_RAW(sub_822590E8) { g_census.Hit(320, ctx); __imp__sub_822590E8(ctx, base); }
REX_HOOK_RAW(sub_822590F8) { g_census.Hit(321, ctx); __imp__sub_822590F8(ctx, base); }
REX_HOOK_RAW(sub_82259118) { g_census.Hit(322, ctx); __imp__sub_82259118(ctx, base); }
REX_HOOK_RAW(sub_82259140) { g_census.Hit(323, ctx); __imp__sub_82259140(ctx, base); }
REX_HOOK_RAW(sub_82259168) { g_census.Hit(324, ctx); __imp__sub_82259168(ctx, base); }
REX_HOOK_RAW(sub_82259190) { g_census.Hit(325, ctx); __imp__sub_82259190(ctx, base); }
REX_HOOK_RAW(sub_822591B8) { g_census.Hit(326, ctx); __imp__sub_822591B8(ctx, base); }
REX_HOOK_RAW(sub_822591E0) { g_census.Hit(327, ctx); __imp__sub_822591E0(ctx, base); }
REX_HOOK_RAW(sub_82259208) { g_census.Hit(328, ctx); __imp__sub_82259208(ctx, base); }
REX_HOOK_RAW(sub_82259228) { g_census.Hit(329, ctx); __imp__sub_82259228(ctx, base); }
REX_HOOK_RAW(sub_82259248) { g_census.Hit(330, ctx); __imp__sub_82259248(ctx, base); }
REX_HOOK_RAW(sub_82259270) { g_census.Hit(331, ctx); __imp__sub_82259270(ctx, base); }
REX_HOOK_RAW(sub_82259298) { g_census.Hit(332, ctx); __imp__sub_82259298(ctx, base); }
REX_HOOK_RAW(sub_822592C0) { g_census.Hit(333, ctx); __imp__sub_822592C0(ctx, base); }
REX_HOOK_RAW(sub_822592E8) { g_census.Hit(334, ctx); __imp__sub_822592E8(ctx, base); }
REX_HOOK_RAW(sub_82259310) { g_census.Hit(335, ctx); __imp__sub_82259310(ctx, base); }
REX_HOOK_RAW(sub_82259338) { g_census.Hit(336, ctx); __imp__sub_82259338(ctx, base); }
REX_HOOK_RAW(sub_82259358) { g_census.Hit(337, ctx); __imp__sub_82259358(ctx, base); }
REX_HOOK_RAW(sub_82259368) { g_census.Hit(338, ctx); __imp__sub_82259368(ctx, base); }
REX_HOOK_RAW(sub_82259378) { g_census.Hit(339, ctx); __imp__sub_82259378(ctx, base); }
REX_HOOK_RAW(sub_82259388) { g_census.Hit(340, ctx); __imp__sub_82259388(ctx, base); }
REX_HOOK_RAW(sub_82259398) { g_census.Hit(341, ctx); __imp__sub_82259398(ctx, base); }
REX_HOOK_RAW(sub_822593A8) { g_census.Hit(342, ctx); __imp__sub_822593A8(ctx, base); }
REX_HOOK_RAW(sub_822593B8) { g_census.Hit(343, ctx); __imp__sub_822593B8(ctx, base); }
REX_HOOK_RAW(sub_822593C8) { g_census.Hit(344, ctx); __imp__sub_822593C8(ctx, base); }
REX_HOOK_RAW(sub_822593D8) { g_census.Hit(345, ctx); __imp__sub_822593D8(ctx, base); }
REX_HOOK_RAW(sub_822593E8) { g_census.Hit(346, ctx); __imp__sub_822593E8(ctx, base); }
REX_HOOK_RAW(sub_822593F8) { g_census.Hit(347, ctx); __imp__sub_822593F8(ctx, base); }
REX_HOOK_RAW(sub_82259408) { g_census.Hit(348, ctx); __imp__sub_82259408(ctx, base); }
REX_HOOK_RAW(sub_82259418) { g_census.Hit(349, ctx); __imp__sub_82259418(ctx, base); }
REX_HOOK_RAW(sub_82259428) { g_census.Hit(350, ctx); __imp__sub_82259428(ctx, base); }
REX_HOOK_RAW(sub_82259438) { g_census.Hit(351, ctx); __imp__sub_82259438(ctx, base); }
REX_HOOK_RAW(sub_82259448) { g_census.Hit(352, ctx); __imp__sub_82259448(ctx, base); }
REX_HOOK_RAW(sub_82259458) { g_census.Hit(353, ctx); __imp__sub_82259458(ctx, base); }
REX_HOOK_RAW(sub_82259498) { g_census.Hit(354, ctx); __imp__sub_82259498(ctx, base); }
REX_HOOK_RAW(sub_822594A8) { g_census.Hit(355, ctx); __imp__sub_822594A8(ctx, base); }
REX_HOOK_RAW(sub_82259538) { g_census.Hit(356, ctx); __imp__sub_82259538(ctx, base); }
REX_HOOK_RAW(sub_82259540) { g_census.Hit(357, ctx); __imp__sub_82259540(ctx, base); }
REX_HOOK_RAW(sub_822595D0) { g_census.Hit(358, ctx); __imp__sub_822595D0(ctx, base); }
REX_HOOK_RAW(sub_822595D8) { g_census.Hit(359, ctx); __imp__sub_822595D8(ctx, base); }
REX_HOOK_RAW(sub_82259668) { g_census.Hit(360, ctx); __imp__sub_82259668(ctx, base); }
REX_HOOK_RAW(sub_82259670) { g_census.Hit(361, ctx); __imp__sub_82259670(ctx, base); }
REX_HOOK_RAW(sub_82259700) { g_census.Hit(362, ctx); __imp__sub_82259700(ctx, base); }
REX_HOOK_RAW(sub_82259708) { g_census.Hit(363, ctx); __imp__sub_82259708(ctx, base); }
REX_HOOK_RAW(sub_82259730) { g_census.Hit(364, ctx); __imp__sub_82259730(ctx, base); }
REX_HOOK_RAW(sub_82259740) { g_census.Hit(365, ctx); __imp__sub_82259740(ctx, base); }
REX_HOOK_RAW(sub_82259768) { g_census.Hit(366, ctx); __imp__sub_82259768(ctx, base); }
REX_HOOK_RAW(sub_82259778) { g_census.Hit(367, ctx); __imp__sub_82259778(ctx, base); }
REX_HOOK_RAW(sub_822597A0) { g_census.Hit(368, ctx); __imp__sub_822597A0(ctx, base); }
REX_HOOK_RAW(sub_822597B0) { g_census.Hit(369, ctx); __imp__sub_822597B0(ctx, base); }
REX_HOOK_RAW(sub_822597D8) { g_census.Hit(370, ctx); __imp__sub_822597D8(ctx, base); }
REX_HOOK_RAW(sub_822597E8) { g_census.Hit(371, ctx); __imp__sub_822597E8(ctx, base); }
REX_HOOK_RAW(sub_82259808) { g_census.Hit(372, ctx); __imp__sub_82259808(ctx, base); }
REX_HOOK_RAW(sub_82259818) { g_census.Hit(373, ctx); __imp__sub_82259818(ctx, base); }
REX_HOOK_RAW(sub_82259838) { g_census.Hit(374, ctx); __imp__sub_82259838(ctx, base); }
REX_HOOK_RAW(sub_82259840) { g_census.Hit(375, ctx); __imp__sub_82259840(ctx, base); }
REX_HOOK_RAW(sub_82259860) { g_census.Hit(376, ctx); __imp__sub_82259860(ctx, base); }
REX_HOOK_RAW(sub_82259870) { g_census.Hit(377, ctx); __imp__sub_82259870(ctx, base); }
REX_HOOK_RAW(sub_82259890) { g_census.Hit(378, ctx); __imp__sub_82259890(ctx, base); }
REX_HOOK_RAW(sub_822598A8) { g_census.Hit(379, ctx); __imp__sub_822598A8(ctx, base); }
REX_HOOK_RAW(sub_822598D0) { g_census.Hit(380, ctx); __imp__sub_822598D0(ctx, base); }
REX_HOOK_RAW(sub_822598D8) { g_census.Hit(381, ctx); __imp__sub_822598D8(ctx, base); }
REX_HOOK_RAW(sub_82259900) { g_census.Hit(382, ctx); __imp__sub_82259900(ctx, base); }
REX_HOOK_RAW(sub_82259908) { g_census.Hit(383, ctx); __imp__sub_82259908(ctx, base); }
REX_HOOK_RAW(sub_82259928) { g_census.Hit(384, ctx); __imp__sub_82259928(ctx, base); }
REX_HOOK_RAW(sub_82259930) { g_census.Hit(385, ctx); __imp__sub_82259930(ctx, base); }
REX_HOOK_RAW(sub_82259958) { g_census.Hit(386, ctx); __imp__sub_82259958(ctx, base); }
REX_HOOK_RAW(sub_82259960) { g_census.Hit(387, ctx); __imp__sub_82259960(ctx, base); }
REX_HOOK_RAW(sub_82259980) { g_census.Hit(388, ctx); __imp__sub_82259980(ctx, base); }
REX_HOOK_RAW(sub_82259990) { g_census.Hit(389, ctx); __imp__sub_82259990(ctx, base); }
REX_HOOK_RAW(sub_822599E8) { g_census.Hit(390, ctx); __imp__sub_822599E8(ctx, base); }
REX_HOOK_RAW(sub_822599F8) { g_census.Hit(391, ctx); __imp__sub_822599F8(ctx, base); }
REX_HOOK_RAW(sub_82259A18) { g_census.Hit(392, ctx); __imp__sub_82259A18(ctx, base); }
REX_HOOK_RAW(sub_82259A28) { g_census.Hit(393, ctx); __imp__sub_82259A28(ctx, base); }
REX_HOOK_RAW(sub_82259A48) { g_census.Hit(394, ctx); __imp__sub_82259A48(ctx, base); }
REX_HOOK_RAW(sub_82259A58) { g_census.Hit(395, ctx); __imp__sub_82259A58(ctx, base); }
REX_HOOK_RAW(sub_82259A78) { g_census.Hit(396, ctx); __imp__sub_82259A78(ctx, base); }
REX_HOOK_RAW(sub_82259A88) { g_census.Hit(397, ctx); __imp__sub_82259A88(ctx, base); }
REX_HOOK_RAW(sub_82259AA0) { g_census.Hit(398, ctx); __imp__sub_82259AA0(ctx, base); }
REX_HOOK_RAW(sub_82259AA8) { g_census.Hit(399, ctx); __imp__sub_82259AA8(ctx, base); }
REX_HOOK_RAW(sub_82259AB0) { g_census.Hit(400, ctx); __imp__sub_82259AB0(ctx, base); }
REX_HOOK_RAW(sub_82259AB8) { g_census.Hit(401, ctx); __imp__sub_82259AB8(ctx, base); }
REX_HOOK_RAW(sub_82259AC8) { g_census.Hit(402, ctx); __imp__sub_82259AC8(ctx, base); }
REX_HOOK_RAW(sub_82259AD8) { g_census.Hit(403, ctx); __imp__sub_82259AD8(ctx, base); }
REX_HOOK_RAW(sub_82259BA0) { g_census.Hit(404, ctx); __imp__sub_82259BA0(ctx, base); }
REX_HOOK_RAW(sub_82259BD8) { g_census.Hit(405, ctx); __imp__sub_82259BD8(ctx, base); }
REX_HOOK_RAW(sub_82259C70) { g_census.Hit(406, ctx); __imp__sub_82259C70(ctx, base); }
REX_HOOK_RAW(sub_82259C80) { g_census.Hit(407, ctx); __imp__sub_82259C80(ctx, base); }
REX_HOOK_RAW(sub_82259D48) { g_census.Hit(408, ctx); __imp__sub_82259D48(ctx, base); }
REX_HOOK_RAW(sub_82259D80) { g_census.Hit(409, ctx); __imp__sub_82259D80(ctx, base); }
REX_HOOK_RAW(sub_82259E10) { g_census.Hit(410, ctx); __imp__sub_82259E10(ctx, base); }
REX_HOOK_RAW(sub_82259E20) { g_census.Hit(411, ctx); __imp__sub_82259E20(ctx, base); }
REX_HOOK_RAW(sub_82259E60) { g_census.Hit(412, ctx); __imp__sub_82259E60(ctx, base); }
REX_HOOK_RAW(sub_82259E78) { g_census.Hit(413, ctx); __imp__sub_82259E78(ctx, base); }
REX_HOOK_RAW(sub_82259F10) { g_census.Hit(414, ctx); __imp__sub_82259F10(ctx, base); }
REX_HOOK_RAW(sub_82259F20) { g_census.Hit(415, ctx); __imp__sub_82259F20(ctx, base); }
REX_HOOK_RAW(sub_82259F88) { g_census.Hit(416, ctx); __imp__sub_82259F88(ctx, base); }
REX_HOOK_RAW(sub_82259F98) { g_census.Hit(417, ctx); __imp__sub_82259F98(ctx, base); }
REX_HOOK_RAW(sub_82259FF8) { g_census.Hit(418, ctx); __imp__sub_82259FF8(ctx, base); }
REX_HOOK_RAW(sub_8225A040) { g_census.Hit(419, ctx); __imp__sub_8225A040(ctx, base); }
REX_HOOK_RAW(sub_8225A0A0) { g_census.Hit(420, ctx); __imp__sub_8225A0A0(ctx, base); }
REX_HOOK_RAW(sub_8225A0E0) { g_census.Hit(421, ctx); __imp__sub_8225A0E0(ctx, base); }
REX_HOOK_RAW(sub_8225A150) { g_census.Hit(422, ctx); __imp__sub_8225A150(ctx, base); }
REX_HOOK_RAW(sub_8225A160) { g_census.Hit(423, ctx); __imp__sub_8225A160(ctx, base); }
REX_HOOK_RAW(sub_8225A1D0) { g_census.Hit(424, ctx); __imp__sub_8225A1D0(ctx, base); }
REX_HOOK_RAW(sub_8225A1E0) { g_census.Hit(425, ctx); __imp__sub_8225A1E0(ctx, base); }
REX_HOOK_RAW(sub_8225A230) { g_census.Hit(426, ctx); __imp__sub_8225A230(ctx, base); }
REX_HOOK_RAW(sub_8225A250) { g_census.Hit(427, ctx); __imp__sub_8225A250(ctx, base); }
REX_HOOK_RAW(sub_8225A288) { g_census.Hit(428, ctx); __imp__sub_8225A288(ctx, base); }
REX_HOOK_RAW(sub_8225A2A0) { g_census.Hit(429, ctx); __imp__sub_8225A2A0(ctx, base); }
REX_HOOK_RAW(sub_8225A2D8) { g_census.Hit(430, ctx); __imp__sub_8225A2D8(ctx, base); }
REX_HOOK_RAW(sub_8225A2F0) { g_census.Hit(431, ctx); __imp__sub_8225A2F0(ctx, base); }
REX_HOOK_RAW(sub_8225A328) { g_census.Hit(432, ctx); __imp__sub_8225A328(ctx, base); }
REX_HOOK_RAW(sub_8225A340) { g_census.Hit(433, ctx); __imp__sub_8225A340(ctx, base); }
REX_HOOK_RAW(sub_8225A380) { g_census.Hit(434, ctx); __imp__sub_8225A380(ctx, base); }
REX_HOOK_RAW(sub_8225A398) { g_census.Hit(435, ctx); __imp__sub_8225A398(ctx, base); }
REX_HOOK_RAW(sub_8225A3D8) { g_census.Hit(436, ctx); __imp__sub_8225A3D8(ctx, base); }
REX_HOOK_RAW(sub_8225A3F0) { g_census.Hit(437, ctx); __imp__sub_8225A3F0(ctx, base); }
REX_HOOK_RAW(sub_8225A430) { g_census.Hit(438, ctx); __imp__sub_8225A430(ctx, base); }
REX_HOOK_RAW(sub_8225A448) { g_census.Hit(439, ctx); __imp__sub_8225A448(ctx, base); }
REX_HOOK_RAW(sub_8225A488) { g_census.Hit(440, ctx); __imp__sub_8225A488(ctx, base); }
REX_HOOK_RAW(sub_8225A4A0) { g_census.Hit(441, ctx); __imp__sub_8225A4A0(ctx, base); }
REX_HOOK_RAW(sub_8225A4E8) { g_census.Hit(442, ctx); __imp__sub_8225A4E8(ctx, base); }
REX_HOOK_RAW(sub_8225A500) { g_census.Hit(443, ctx); __imp__sub_8225A500(ctx, base); }
REX_HOOK_RAW(sub_8225A5F8) { g_census.Hit(444, ctx); __imp__sub_8225A5F8(ctx, base); }
REX_HOOK_RAW(sub_8225A648) { g_census.Hit(445, ctx); __imp__sub_8225A648(ctx, base); }
REX_HOOK_RAW(sub_8225A768) { g_census.Hit(446, ctx); __imp__sub_8225A768(ctx, base); }
REX_HOOK_RAW(sub_8225A7F8) { g_census.Hit(447, ctx); __imp__sub_8225A7F8(ctx, base); }
REX_HOOK_RAW(sub_8225A840) { g_census.Hit(448, ctx); __imp__sub_8225A840(ctx, base); }
REX_HOOK_RAW(sub_8225A880) { g_census.Hit(449, ctx); __imp__sub_8225A880(ctx, base); }
REX_HOOK_RAW(sub_8225A8C0) { g_census.Hit(450, ctx); __imp__sub_8225A8C0(ctx, base); }
REX_HOOK_RAW(sub_8225A990) { g_census.Hit(451, ctx); __imp__sub_8225A990(ctx, base); }
REX_HOOK_RAW(sub_8225AA60) { g_census.Hit(452, ctx); __imp__sub_8225AA60(ctx, base); }
REX_HOOK_RAW(sub_8225AB58) { g_census.Hit(453, ctx); __imp__sub_8225AB58(ctx, base); }
REX_HOOK_RAW(sub_8225ADB0) { g_census.Hit(454, ctx); __imp__sub_8225ADB0(ctx, base); }
REX_HOOK_RAW(sub_8225ADC0) { g_census.Hit(455, ctx); __imp__sub_8225ADC0(ctx, base); }
REX_HOOK_RAW(sub_8225AE40) { g_census.Hit(456, ctx); __imp__sub_8225AE40(ctx, base); }
REX_HOOK_RAW(sub_8225AE60) { g_census.Hit(457, ctx); __imp__sub_8225AE60(ctx, base); }
REX_HOOK_RAW(sub_8225AEF0) { g_census.Hit(458, ctx); __imp__sub_8225AEF0(ctx, base); }
REX_HOOK_RAW(sub_8225B238) { g_census.Hit(459, ctx); __imp__sub_8225B238(ctx, base); }
REX_HOOK_RAW(sub_8225B510) { g_census.Hit(460, ctx); __imp__sub_8225B510(ctx, base); }
REX_HOOK_RAW(sub_8225B518) { g_census.Hit(461, ctx); __imp__sub_8225B518(ctx, base); }
REX_HOOK_RAW(sub_8225B588) { g_census.Hit(462, ctx); __imp__sub_8225B588(ctx, base); }
REX_HOOK_RAW(sub_8225B6A0) { g_census.Hit(463, ctx); __imp__sub_8225B6A0(ctx, base); }
REX_HOOK_RAW(sub_8225B850) { g_census.Hit(464, ctx); __imp__sub_8225B850(ctx, base); }
REX_HOOK_RAW(sub_8225BA30) { g_census.Hit(465, ctx); __imp__sub_8225BA30(ctx, base); }
REX_HOOK_RAW(sub_8225BAD8) { g_census.Hit(466, ctx); __imp__sub_8225BAD8(ctx, base); }
REX_HOOK_RAW(sub_8225BB58) { g_census.Hit(467, ctx); __imp__sub_8225BB58(ctx, base); }
REX_HOOK_RAW(sub_8225BD38) { g_census.Hit(468, ctx); __imp__sub_8225BD38(ctx, base); }
REX_HOOK_RAW(sub_8225BD40) { g_census.Hit(469, ctx); __imp__sub_8225BD40(ctx, base); }
REX_HOOK_RAW(sub_8225C350) { g_census.Hit(470, ctx); __imp__sub_8225C350(ctx, base); }
REX_HOOK_RAW(sub_8225C480) { g_census.Hit(471, ctx); __imp__sub_8225C480(ctx, base); }
REX_HOOK_RAW(sub_8225C538) { g_census.Hit(472, ctx); __imp__sub_8225C538(ctx, base); }
REX_HOOK_RAW(sub_8225C730) { g_census.Hit(473, ctx); __imp__sub_8225C730(ctx, base); }
REX_HOOK_RAW(sub_8225CAC8) { g_census.Hit(474, ctx); __imp__sub_8225CAC8(ctx, base); }
REX_HOOK_RAW(sub_8225CB88) { g_census.Hit(475, ctx); __imp__sub_8225CB88(ctx, base); }
REX_HOOK_RAW(sub_8225CD08) { g_census.Hit(476, ctx); __imp__sub_8225CD08(ctx, base); }
REX_HOOK_RAW(sub_8225CE60) { g_census.Hit(477, ctx); __imp__sub_8225CE60(ctx, base); }
REX_HOOK_RAW(sub_8225CFB8) { g_census.Hit(478, ctx); __imp__sub_8225CFB8(ctx, base); }
REX_HOOK_RAW(sub_8225D5C8) { g_census.Hit(479, ctx); __imp__sub_8225D5C8(ctx, base); }
REX_HOOK_RAW(sub_8225D698) { g_census.Hit(480, ctx); __imp__sub_8225D698(ctx, base); }
REX_HOOK_RAW(sub_8225D750) { g_census.Hit(481, ctx); __imp__sub_8225D750(ctx, base); }
REX_HOOK_RAW(sub_8225D8A0) { g_census.Hit(482, ctx); __imp__sub_8225D8A0(ctx, base); }
REX_HOOK_RAW(sub_8225DA00) { g_census.Hit(483, ctx); __imp__sub_8225DA00(ctx, base); }
REX_HOOK_RAW(sub_8225DB48) { g_census.Hit(484, ctx); __imp__sub_8225DB48(ctx, base); }
REX_HOOK_RAW(sub_8225DC88) { g_census.Hit(485, ctx); __imp__sub_8225DC88(ctx, base); }
REX_HOOK_RAW(sub_8225E518) { g_census.Hit(486, ctx); __imp__sub_8225E518(ctx, base); }
REX_HOOK_RAW(sub_8225E688) { g_census.Hit(487, ctx); __imp__sub_8225E688(ctx, base); }
REX_HOOK_RAW(sub_8225E698) { g_census.Hit(488, ctx); __imp__sub_8225E698(ctx, base); }
REX_HOOK_RAW(sub_8225E6B0) { g_census.Hit(489, ctx); __imp__sub_8225E6B0(ctx, base); }
REX_HOOK_RAW(sub_8225E730) { g_census.Hit(490, ctx); __imp__sub_8225E730(ctx, base); }
REX_HOOK_RAW(sub_8225E998) { g_census.Hit(491, ctx); __imp__sub_8225E998(ctx, base); }
REX_HOOK_RAW(sub_8225EA90) { g_census.Hit(492, ctx); __imp__sub_8225EA90(ctx, base); }
REX_HOOK_RAW(sub_8225EE20) { g_census.Hit(493, ctx); __imp__sub_8225EE20(ctx, base); }
REX_HOOK_RAW(sub_8225EEE0) { g_census.Hit(494, ctx); __imp__sub_8225EEE0(ctx, base); }
REX_HOOK_RAW(sub_8225EF28) { g_census.Hit(495, ctx); __imp__sub_8225EF28(ctx, base); }
REX_HOOK_RAW(sub_8225EF48) { g_census.Hit(496, ctx); __imp__sub_8225EF48(ctx, base); }
REX_HOOK_RAW(sub_8225EF88) { g_census.Hit(497, ctx); __imp__sub_8225EF88(ctx, base); }
REX_HOOK_RAW(sub_8225EFB0) { g_census.Hit(498, ctx); __imp__sub_8225EFB0(ctx, base); }
REX_HOOK_RAW(sub_8225F218) { g_census.Hit(499, ctx); __imp__sub_8225F218(ctx, base); }
REX_HOOK_RAW(sub_8225F468) { g_census.Hit(500, ctx); __imp__sub_8225F468(ctx, base); }
REX_HOOK_RAW(sub_8225F518) { g_census.Hit(501, ctx); __imp__sub_8225F518(ctx, base); }
REX_HOOK_RAW(sub_8225F570) { g_census.Hit(502, ctx); __imp__sub_8225F570(ctx, base); }
REX_HOOK_RAW(sub_8225F618) { g_census.Hit(503, ctx); __imp__sub_8225F618(ctx, base); }
REX_HOOK_RAW(sub_8225F6B0) { g_census.Hit(504, ctx); __imp__sub_8225F6B0(ctx, base); }
REX_HOOK_RAW(sub_8225F728) { g_census.Hit(505, ctx); __imp__sub_8225F728(ctx, base); }
REX_HOOK_RAW(sub_8225F940) { g_census.Hit(506, ctx); __imp__sub_8225F940(ctx, base); }
REX_HOOK_RAW(sub_8225F990) { g_census.Hit(507, ctx); __imp__sub_8225F990(ctx, base); }
REX_HOOK_RAW(sub_8225FA10) { g_census.Hit(508, ctx); __imp__sub_8225FA10(ctx, base); }
REX_HOOK_RAW(sub_8225FB90) { g_census.Hit(509, ctx); __imp__sub_8225FB90(ctx, base); }
REX_HOOK_RAW(sub_822600C8) { g_census.Hit(510, ctx); __imp__sub_822600C8(ctx, base); }
REX_HOOK_RAW(sub_822602A0) { g_census.Hit(511, ctx); __imp__sub_822602A0(ctx, base); }
REX_HOOK_RAW(sub_822603B8) { g_census.Hit(512, ctx); __imp__sub_822603B8(ctx, base); }
REX_HOOK_RAW(sub_82260418) { g_census.Hit(513, ctx); __imp__sub_82260418(ctx, base); }
REX_HOOK_RAW(sub_82260548) { g_census.Hit(514, ctx); __imp__sub_82260548(ctx, base); }
REX_HOOK_RAW(sub_82260558) { g_census.Hit(515, ctx); __imp__sub_82260558(ctx, base); }
REX_HOOK_RAW(sub_82260638) { g_census.Hit(516, ctx); __imp__sub_82260638(ctx, base); }
REX_HOOK_RAW(sub_82260718) { g_census.Hit(517, ctx); __imp__sub_82260718(ctx, base); }
REX_HOOK_RAW(sub_82260778) { g_census.Hit(518, ctx); __imp__sub_82260778(ctx, base); }
REX_HOOK_RAW(sub_822607D8) { g_census.Hit(519, ctx); __imp__sub_822607D8(ctx, base); }
REX_HOOK_RAW(sub_82260830) { g_census.Hit(520, ctx); __imp__sub_82260830(ctx, base); }
REX_HOOK_RAW(sub_82260888) { g_census.Hit(521, ctx); __imp__sub_82260888(ctx, base); }
REX_HOOK_RAW(sub_82260A48) { g_census.Hit(522, ctx); __imp__sub_82260A48(ctx, base); }
REX_HOOK_RAW(sub_82260A90) { g_census.Hit(523, ctx); __imp__sub_82260A90(ctx, base); }
REX_HOOK_RAW(sub_82260B88) { g_census.Hit(524, ctx); __imp__sub_82260B88(ctx, base); }
REX_HOOK_RAW(sub_82260D58) { g_census.Hit(525, ctx); __imp__sub_82260D58(ctx, base); }
REX_HOOK_RAW(sub_82260DA0) { g_census.Hit(526, ctx); __imp__sub_82260DA0(ctx, base); }
REX_HOOK_RAW(sub_82260DB8) { g_census.Hit(527, ctx); __imp__sub_82260DB8(ctx, base); }
REX_HOOK_RAW(sub_82260EA8) { g_census.Hit(528, ctx); __imp__sub_82260EA8(ctx, base); }
REX_HOOK_RAW(sub_82260F30) { g_census.Hit(529, ctx); __imp__sub_82260F30(ctx, base); }
REX_HOOK_RAW(sub_82261018) { g_census.Hit(530, ctx); __imp__sub_82261018(ctx, base); }
REX_HOOK_RAW(sub_82261260) { g_census.Hit(531, ctx); __imp__sub_82261260(ctx, base); }
REX_HOOK_RAW(sub_822612B0) { g_census.Hit(532, ctx); __imp__sub_822612B0(ctx, base); }
REX_HOOK_RAW(sub_82261300) { g_census.Hit(533, ctx); __imp__sub_82261300(ctx, base); }
REX_HOOK_RAW(sub_822613B0) { g_census.Hit(534, ctx); __imp__sub_822613B0(ctx, base); }
REX_HOOK_RAW(sub_82261460) { g_census.Hit(535, ctx); __imp__sub_82261460(ctx, base); }
REX_HOOK_RAW(sub_822615E8) { g_census.Hit(536, ctx); __imp__sub_822615E8(ctx, base); }
REX_HOOK_RAW(sub_82261680) { g_census.Hit(537, ctx); __imp__sub_82261680(ctx, base); }
REX_HOOK_RAW(sub_82261708) { g_census.Hit(538, ctx); __imp__sub_82261708(ctx, base); }
REX_HOOK_RAW(sub_82261800) { g_census.Hit(539, ctx); __imp__sub_82261800(ctx, base); }
REX_HOOK_RAW(sub_82261900) { g_census.Hit(540, ctx); __imp__sub_82261900(ctx, base); }
REX_HOOK_RAW(sub_8226194C) { g_census.Hit(541, ctx); __imp__sub_8226194C(ctx, base); }
REX_HOOK_RAW(sub_82261950) { g_census.Hit(542, ctx); __imp__sub_82261950(ctx, base); }
REX_HOOK_RAW(sub_822619B8) { g_census.Hit(543, ctx); __imp__sub_822619B8(ctx, base); }
REX_HOOK_RAW(sub_822619C0) { g_census.Hit(544, ctx); __imp__sub_822619C0(ctx, base); }
REX_HOOK_RAW(sub_822619D8) { g_census.Hit(545, ctx); __imp__sub_822619D8(ctx, base); }
REX_HOOK_RAW(sub_82261A48) { g_census.Hit(546, ctx); __imp__sub_82261A48(ctx, base); }
REX_HOOK_RAW(sub_82261B30) { g_census.Hit(547, ctx); __imp__sub_82261B30(ctx, base); }
REX_HOOK_RAW(sub_82261BD0) { g_census.Hit(548, ctx); __imp__sub_82261BD0(ctx, base); }
REX_HOOK_RAW(sub_822621D8) { g_census.Hit(549, ctx); __imp__sub_822621D8(ctx, base); }
REX_HOOK_RAW(sub_822621F0) { g_census.Hit(550, ctx); __imp__sub_822621F0(ctx, base); }
REX_HOOK_RAW(sub_82263878) { g_census.Hit(551, ctx); __imp__sub_82263878(ctx, base); }
REX_HOOK_RAW(sub_822638E8) { g_census.Hit(552, ctx); __imp__sub_822638E8(ctx, base); }
REX_HOOK_RAW(sub_82263958) { g_census.Hit(553, ctx); __imp__sub_82263958(ctx, base); }
REX_HOOK_RAW(sub_822639B0) { g_census.Hit(554, ctx); __imp__sub_822639B0(ctx, base); }
REX_HOOK_RAW(sub_82263A38) { g_census.Hit(555, ctx); __imp__sub_82263A38(ctx, base); }
REX_HOOK_RAW(sub_82263A98) { g_census.Hit(556, ctx); __imp__sub_82263A98(ctx, base); }
REX_HOOK_RAW(sub_82263BC0) { g_census.Hit(557, ctx); __imp__sub_82263BC0(ctx, base); }
REX_HOOK_RAW(sub_82263BD0) { g_census.Hit(558, ctx); __imp__sub_82263BD0(ctx, base); }
REX_HOOK_RAW(sub_82263C40) { g_census.Hit(559, ctx); __imp__sub_82263C40(ctx, base); }
REX_HOOK_RAW(sub_82263CA8) { g_census.Hit(560, ctx); __imp__sub_82263CA8(ctx, base); }
REX_HOOK_RAW(sub_82263D50) { g_census.Hit(561, ctx); __imp__sub_82263D50(ctx, base); }
REX_HOOK_RAW(sub_82263DE8) { g_census.Hit(562, ctx); __imp__sub_82263DE8(ctx, base); }
REX_HOOK_RAW(sub_82263E40) { g_census.Hit(563, ctx); __imp__sub_82263E40(ctx, base); }
REX_HOOK_RAW(sub_82263EB8) { g_census.Hit(564, ctx); __imp__sub_82263EB8(ctx, base); }
REX_HOOK_RAW(sub_82263F90) { g_census.Hit(565, ctx); __imp__sub_82263F90(ctx, base); }
REX_HOOK_RAW(sub_82264058) { g_census.Hit(566, ctx); __imp__sub_82264058(ctx, base); }
REX_HOOK_RAW(sub_822640C0) { g_census.Hit(567, ctx); __imp__sub_822640C0(ctx, base); }
REX_HOOK_RAW(sub_82264118) { g_census.Hit(568, ctx); __imp__sub_82264118(ctx, base); }
REX_HOOK_RAW(sub_82264160) { g_census.Hit(569, ctx); __imp__sub_82264160(ctx, base); }
REX_HOOK_RAW(sub_822642B8) { g_census.Hit(570, ctx); __imp__sub_822642B8(ctx, base); }
REX_HOOK_RAW(sub_82264358) { g_census.Hit(571, ctx); __imp__sub_82264358(ctx, base); }
REX_HOOK_RAW(sub_82264468) { g_census.Hit(572, ctx); __imp__sub_82264468(ctx, base); }
REX_HOOK_RAW(sub_822648B8) { g_census.Hit(573, ctx); __imp__sub_822648B8(ctx, base); }
REX_HOOK_RAW(sub_82264D98) { g_census.Hit(574, ctx); __imp__sub_82264D98(ctx, base); }
REX_HOOK_RAW(sub_82264DA0) { g_census.Hit(575, ctx); __imp__sub_82264DA0(ctx, base); }
REX_HOOK_RAW(sub_82264F78) { g_census.Hit(576, ctx); __imp__sub_82264F78(ctx, base); }
REX_HOOK_RAW(sub_82265078) { g_census.Hit(577, ctx); __imp__sub_82265078(ctx, base); }
REX_HOOK_RAW(sub_82265130) { g_census.Hit(578, ctx); __imp__sub_82265130(ctx, base); }
REX_HOOK_RAW(sub_822651C0) { g_census.Hit(579, ctx); __imp__sub_822651C0(ctx, base); }
REX_HOOK_RAW(sub_82265298) { g_census.Hit(580, ctx); __imp__sub_82265298(ctx, base); }
REX_HOOK_RAW(sub_82265338) { g_census.Hit(581, ctx); __imp__sub_82265338(ctx, base); }
REX_HOOK_RAW(sub_82265AA0) { g_census.Hit(582, ctx); __imp__sub_82265AA0(ctx, base); }
REX_HOOK_RAW(sub_82265F20) { g_census.Hit(583, ctx); __imp__sub_82265F20(ctx, base); }
REX_HOOK_RAW(sub_82266248) { g_census.Hit(584, ctx); __imp__sub_82266248(ctx, base); }
REX_HOOK_RAW(sub_82266938) { g_census.Hit(585, ctx); __imp__sub_82266938(ctx, base); }
REX_HOOK_RAW(sub_82266A68) { g_census.Hit(586, ctx); __imp__sub_82266A68(ctx, base); }
REX_HOOK_RAW(sub_82266BE0) { g_census.Hit(587, ctx); __imp__sub_82266BE0(ctx, base); }
REX_HOOK_RAW(sub_82266E80) { g_census.Hit(588, ctx); __imp__sub_82266E80(ctx, base); }
REX_HOOK_RAW(sub_82266FA8) { g_census.Hit(589, ctx); __imp__sub_82266FA8(ctx, base); }
REX_HOOK_RAW(sub_82267020) { g_census.Hit(590, ctx); __imp__sub_82267020(ctx, base); }
REX_HOOK_RAW(sub_82267080) { g_census.Hit(591, ctx); __imp__sub_82267080(ctx, base); }
REX_HOOK_RAW(sub_82267120) { g_census.Hit(592, ctx); __imp__sub_82267120(ctx, base); }
REX_HOOK_RAW(sub_82267218) { g_census.Hit(593, ctx); __imp__sub_82267218(ctx, base); }
REX_HOOK_RAW(sub_82267448) { g_census.Hit(594, ctx); __imp__sub_82267448(ctx, base); }
REX_HOOK_RAW(sub_822674D0) { g_census.Hit(595, ctx); __imp__sub_822674D0(ctx, base); }
REX_HOOK_RAW(sub_82267930) { g_census.Hit(596, ctx); __imp__sub_82267930(ctx, base); }
REX_HOOK_RAW(sub_82267AA8) { g_census.Hit(597, ctx); __imp__sub_82267AA8(ctx, base); }
REX_HOOK_RAW(sub_82267B00) { g_census.Hit(598, ctx); __imp__sub_82267B00(ctx, base); }
REX_HOOK_RAW(sub_82267C08) { g_census.Hit(599, ctx); __imp__sub_82267C08(ctx, base); }
REX_HOOK_RAW(sub_82267D10) { g_census.Hit(600, ctx); __imp__sub_82267D10(ctx, base); }
REX_HOOK_RAW(sub_82268190) { g_census.Hit(601, ctx); __imp__sub_82268190(ctx, base); }
REX_HOOK_RAW(sub_82268470) { g_census.Hit(602, ctx); __imp__sub_82268470(ctx, base); }
REX_HOOK_RAW(sub_82268998) { g_census.Hit(603, ctx); __imp__sub_82268998(ctx, base); }
REX_HOOK_RAW(sub_82268B48) { g_census.Hit(604, ctx); __imp__sub_82268B48(ctx, base); }
REX_HOOK_RAW(sub_82268BC8) { g_census.Hit(605, ctx); __imp__sub_82268BC8(ctx, base); }
REX_HOOK_RAW(sub_82268BF8) { g_census.Hit(606, ctx); __imp__sub_82268BF8(ctx, base); }
REX_HOOK_RAW(sub_82268CE0) { g_census.Hit(607, ctx); __imp__sub_82268CE0(ctx, base); }
REX_HOOK_RAW(sub_82268CF8) { g_census.Hit(608, ctx); __imp__sub_82268CF8(ctx, base); }
REX_HOOK_RAW(sub_82268D10) { g_census.Hit(609, ctx); __imp__sub_82268D10(ctx, base); }
REX_HOOK_RAW(sub_82268D48) { g_census.Hit(610, ctx); __imp__sub_82268D48(ctx, base); }
REX_HOOK_RAW(sub_82268DA0) { g_census.Hit(611, ctx); __imp__sub_82268DA0(ctx, base); }
REX_HOOK_RAW(sub_82268DE8) { g_census.Hit(612, ctx); __imp__sub_82268DE8(ctx, base); }
REX_HOOK_RAW(sub_82268E00) { g_census.Hit(613, ctx); __imp__sub_82268E00(ctx, base); }
REX_HOOK_RAW(sub_82268E18) { g_census.Hit(614, ctx); __imp__sub_82268E18(ctx, base); }
REX_HOOK_RAW(sub_82268E40) { g_census.Hit(615, ctx); __imp__sub_82268E40(ctx, base); }
REX_HOOK_RAW(sub_82269100) { g_census.Hit(616, ctx); __imp__sub_82269100(ctx, base); }
REX_HOOK_RAW(sub_82269180) { g_census.Hit(617, ctx); __imp__sub_82269180(ctx, base); }
REX_HOOK_RAW(sub_82269290) { g_census.Hit(618, ctx); __imp__sub_82269290(ctx, base); }
REX_HOOK_RAW(sub_82269FB0) { g_census.Hit(619, ctx); __imp__sub_82269FB0(ctx, base); }
REX_HOOK_RAW(sub_8226A068) { g_census.Hit(620, ctx); __imp__sub_8226A068(ctx, base); }
REX_HOOK_RAW(sub_8226A490) { g_census.Hit(621, ctx); __imp__sub_8226A490(ctx, base); }
REX_HOOK_RAW(sub_8226AD68) { g_census.Hit(622, ctx); __imp__sub_8226AD68(ctx, base); }
REX_HOOK_RAW(sub_8226AD98) { g_census.Hit(623, ctx); __imp__sub_8226AD98(ctx, base); }
REX_HOOK_RAW(sub_8226B108) { g_census.Hit(624, ctx); __imp__sub_8226B108(ctx, base); }
REX_HOOK_RAW(sub_8226B1F8) { g_census.Hit(625, ctx); __imp__sub_8226B1F8(ctx, base); }
REX_HOOK_RAW(sub_8226B248) { g_census.Hit(626, ctx); __imp__sub_8226B248(ctx, base); }
REX_HOOK_RAW(sub_8226B2F0) { g_census.Hit(627, ctx); __imp__sub_8226B2F0(ctx, base); }
REX_HOOK_RAW(sub_8226B358) { g_census.Hit(628, ctx); __imp__sub_8226B358(ctx, base); }
REX_HOOK_RAW(sub_8226B478) { g_census.Hit(629, ctx); __imp__sub_8226B478(ctx, base); }
REX_HOOK_RAW(sub_8226B8A0) { g_census.Hit(630, ctx); __imp__sub_8226B8A0(ctx, base); }
REX_HOOK_RAW(sub_8226B978) { g_census.Hit(631, ctx); __imp__sub_8226B978(ctx, base); }
REX_HOOK_RAW(sub_8226C7D0) { g_census.Hit(632, ctx); __imp__sub_8226C7D0(ctx, base); }
REX_HOOK_RAW(sub_8226C848) { g_census.Hit(633, ctx); __imp__sub_8226C848(ctx, base); }
REX_HOOK_RAW(sub_8226C900) { g_census.Hit(634, ctx); __imp__sub_8226C900(ctx, base); }
REX_HOOK_RAW(sub_8226C968) { g_census.Hit(635, ctx); __imp__sub_8226C968(ctx, base); }
REX_HOOK_RAW(sub_8226CA70) { g_census.Hit(636, ctx); __imp__sub_8226CA70(ctx, base); }
REX_HOOK_RAW(sub_8226CAD0) { g_census.Hit(637, ctx); __imp__sub_8226CAD0(ctx, base); }
REX_HOOK_RAW(sub_8226CC70) { g_census.Hit(638, ctx); __imp__sub_8226CC70(ctx, base); }
REX_HOOK_RAW(sub_8226CCF8) { g_census.Hit(639, ctx); __imp__sub_8226CCF8(ctx, base); }
REX_HOOK_RAW(sub_8226CD98) { g_census.Hit(640, ctx); __imp__sub_8226CD98(ctx, base); }
REX_HOOK_RAW(sub_8226CE60) { g_census.Hit(641, ctx); __imp__sub_8226CE60(ctx, base); }
REX_HOOK_RAW(sub_8226CF98) { g_census.Hit(642, ctx); __imp__sub_8226CF98(ctx, base); }
REX_HOOK_RAW(sub_8226D090) { g_census.Hit(643, ctx); __imp__sub_8226D090(ctx, base); }
REX_HOOK_RAW(sub_8226D3D0) { g_census.Hit(644, ctx); __imp__sub_8226D3D0(ctx, base); }
REX_HOOK_RAW(sub_8226D518) { g_census.Hit(645, ctx); __imp__sub_8226D518(ctx, base); }
REX_HOOK_RAW(sub_8226D830) { g_census.Hit(646, ctx); __imp__sub_8226D830(ctx, base); }
REX_HOOK_RAW(sub_8226D9C0) { g_census.Hit(647, ctx); __imp__sub_8226D9C0(ctx, base); }
REX_HOOK_RAW(sub_8226DB40) { g_census.Hit(648, ctx); __imp__sub_8226DB40(ctx, base); }
REX_HOOK_RAW(sub_8226DBD8) { g_census.Hit(649, ctx); __imp__sub_8226DBD8(ctx, base); }
REX_HOOK_RAW(sub_8226DEC8) { g_census.Hit(650, ctx); __imp__sub_8226DEC8(ctx, base); }
REX_HOOK_RAW(sub_8226E168) { g_census.Hit(651, ctx); __imp__sub_8226E168(ctx, base); }
REX_HOOK_RAW(sub_8226E6D0) { g_census.Hit(652, ctx); __imp__sub_8226E6D0(ctx, base); }
REX_HOOK_RAW(sub_8226ED80) { g_census.Hit(653, ctx); __imp__sub_8226ED80(ctx, base); }
REX_HOOK_RAW(sub_8226EEA8) { g_census.Hit(654, ctx); __imp__sub_8226EEA8(ctx, base); }
REX_HOOK_RAW(sub_8226EF68) { g_census.Hit(655, ctx); __imp__sub_8226EF68(ctx, base); }
REX_HOOK_RAW(sub_8226F138) { g_census.Hit(656, ctx); __imp__sub_8226F138(ctx, base); }
REX_HOOK_RAW(sub_8226F200) { g_census.Hit(657, ctx); __imp__sub_8226F200(ctx, base); }
REX_HOOK_RAW(sub_8226F268) { g_census.Hit(658, ctx); __imp__sub_8226F268(ctx, base); }
REX_HOOK_RAW(sub_8226F2C8) { g_census.Hit(659, ctx); __imp__sub_8226F2C8(ctx, base); }
REX_HOOK_RAW(sub_8226F328) { g_census.Hit(660, ctx); __imp__sub_8226F328(ctx, base); }
REX_HOOK_RAW(sub_8226F388) { g_census.Hit(661, ctx); __imp__sub_8226F388(ctx, base); }
REX_HOOK_RAW(sub_8226F5E0) { g_census.Hit(662, ctx); __imp__sub_8226F5E0(ctx, base); }
REX_HOOK_RAW(sub_8226F698) { g_census.Hit(663, ctx); __imp__sub_8226F698(ctx, base); }
REX_HOOK_RAW(sub_8226F6A8) { g_census.Hit(664, ctx); __imp__sub_8226F6A8(ctx, base); }
REX_HOOK_RAW(sub_8226F6B0) { g_census.Hit(665, ctx); __imp__sub_8226F6B0(ctx, base); }
REX_HOOK_RAW(sub_8226F6C0) { g_census.Hit(666, ctx); __imp__sub_8226F6C0(ctx, base); }
REX_HOOK_RAW(sub_8226F6D8) { g_census.Hit(667, ctx); __imp__sub_8226F6D8(ctx, base); }
REX_HOOK_RAW(sub_8226F6F0) { g_census.Hit(668, ctx); __imp__sub_8226F6F0(ctx, base); }
REX_HOOK_RAW(sub_8226F708) { g_census.Hit(669, ctx); __imp__sub_8226F708(ctx, base); }
REX_HOOK_RAW(sub_8226F718) { g_census.Hit(670, ctx); __imp__sub_8226F718(ctx, base); }
REX_HOOK_RAW(sub_8226F728) { g_census.Hit(671, ctx); __imp__sub_8226F728(ctx, base); }
REX_HOOK_RAW(sub_8226F738) { g_census.Hit(672, ctx); __imp__sub_8226F738(ctx, base); }
REX_HOOK_RAW(sub_8226F750) { g_census.Hit(673, ctx); __imp__sub_8226F750(ctx, base); }
REX_HOOK_RAW(sub_8226F760) { g_census.Hit(674, ctx); __imp__sub_8226F760(ctx, base); }
REX_HOOK_RAW(sub_8226F780) { g_census.Hit(675, ctx); __imp__sub_8226F780(ctx, base); }
REX_HOOK_RAW(sub_8226F7E0) { g_census.Hit(676, ctx); __imp__sub_8226F7E0(ctx, base); }
REX_HOOK_RAW(sub_8226F7F8) { g_census.Hit(677, ctx); __imp__sub_8226F7F8(ctx, base); }
REX_HOOK_RAW(sub_8226F808) { g_census.Hit(678, ctx); __imp__sub_8226F808(ctx, base); }
REX_HOOK_RAW(sub_8226F818) { g_census.Hit(679, ctx); __imp__sub_8226F818(ctx, base); }
REX_HOOK_RAW(sub_8226F820) { g_census.Hit(680, ctx); __imp__sub_8226F820(ctx, base); }
REX_HOOK_RAW(sub_8226F888) { g_census.Hit(681, ctx); __imp__sub_8226F888(ctx, base); }
REX_HOOK_RAW(sub_8226F890) { g_census.Hit(682, ctx); __imp__sub_8226F890(ctx, base); }
REX_HOOK_RAW(sub_8226F898) { g_census.Hit(683, ctx); __imp__sub_8226F898(ctx, base); }
REX_HOOK_RAW(sub_8226F8A0) { g_census.Hit(684, ctx); __imp__sub_8226F8A0(ctx, base); }
REX_HOOK_RAW(sub_8226F8A8) { g_census.Hit(685, ctx); __imp__sub_8226F8A8(ctx, base); }
REX_HOOK_RAW(sub_8226F930) { g_census.Hit(686, ctx); __imp__sub_8226F930(ctx, base); }
REX_HOOK_RAW(sub_8226F9A0) { g_census.Hit(687, ctx); __imp__sub_8226F9A0(ctx, base); }
REX_HOOK_RAW(sub_8226FB78) { g_census.Hit(688, ctx); __imp__sub_8226FB78(ctx, base); }
REX_HOOK_RAW(sub_8226FC30) { g_census.Hit(689, ctx); __imp__sub_8226FC30(ctx, base); }
REX_HOOK_RAW(sub_8226FC80) { g_census.Hit(690, ctx); __imp__sub_8226FC80(ctx, base); }
REX_HOOK_RAW(sub_8226FCC8) { g_census.Hit(691, ctx); __imp__sub_8226FCC8(ctx, base); }
REX_HOOK_RAW(sub_8226FD20) { g_census.Hit(692, ctx); __imp__sub_8226FD20(ctx, base); }
REX_HOOK_RAW(sub_8226FD68) { g_census.Hit(693, ctx); __imp__sub_8226FD68(ctx, base); }
REX_HOOK_RAW(sub_8226FDB8) { g_census.Hit(694, ctx); __imp__sub_8226FDB8(ctx, base); }
REX_HOOK_RAW(sub_8226FE20) { g_census.Hit(695, ctx); __imp__sub_8226FE20(ctx, base); }
REX_HOOK_RAW(sub_8226FE30) { g_census.Hit(696, ctx); __imp__sub_8226FE30(ctx, base); }
REX_HOOK_RAW(sub_8226FE70) { g_census.Hit(697, ctx); __imp__sub_8226FE70(ctx, base); }
REX_HOOK_RAW(sub_8226FEB0) { g_census.Hit(698, ctx); __imp__sub_8226FEB0(ctx, base); }
REX_HOOK_RAW(sub_8226FF20) { g_census.Hit(699, ctx); __imp__sub_8226FF20(ctx, base); }
REX_HOOK_RAW(sub_8226FF58) { g_census.Hit(700, ctx); __imp__sub_8226FF58(ctx, base); }
REX_HOOK_RAW(sub_8226FFC8) { g_census.Hit(701, ctx); __imp__sub_8226FFC8(ctx, base); }
REX_HOOK_RAW(sub_82270000) { g_census.Hit(702, ctx); __imp__sub_82270000(ctx, base); }
REX_HOOK_RAW(sub_82270010) { g_census.Hit(703, ctx); __imp__sub_82270010(ctx, base); }
REX_HOOK_RAW(sub_82270020) { g_census.Hit(704, ctx); __imp__sub_82270020(ctx, base); }
REX_HOOK_RAW(sub_822700E0) { g_census.Hit(705, ctx); __imp__sub_822700E0(ctx, base); }
REX_HOOK_RAW(sub_822701B0) { g_census.Hit(706, ctx); __imp__sub_822701B0(ctx, base); }
REX_HOOK_RAW(sub_82270238) { g_census.Hit(707, ctx); __imp__sub_82270238(ctx, base); }
REX_HOOK_RAW(sub_822702B0) { g_census.Hit(708, ctx); __imp__sub_822702B0(ctx, base); }
REX_HOOK_RAW(sub_82270360) { g_census.Hit(709, ctx); __imp__sub_82270360(ctx, base); }
REX_HOOK_RAW(sub_82270410) { g_census.Hit(710, ctx); __imp__sub_82270410(ctx, base); }
REX_HOOK_RAW(sub_82270490) { g_census.Hit(711, ctx); __imp__sub_82270490(ctx, base); }
REX_HOOK_RAW(sub_822704E0) { g_census.Hit(712, ctx); __imp__sub_822704E0(ctx, base); }
REX_HOOK_RAW(sub_822704F8) { g_census.Hit(713, ctx); __imp__sub_822704F8(ctx, base); }
REX_HOOK_RAW(sub_82270570) { g_census.Hit(714, ctx); __imp__sub_82270570(ctx, base); }
REX_HOOK_RAW(sub_822705C8) { g_census.Hit(715, ctx); __imp__sub_822705C8(ctx, base); }
REX_HOOK_RAW(sub_82270638) { g_census.Hit(716, ctx); __imp__sub_82270638(ctx, base); }
REX_HOOK_RAW(sub_82270718) { g_census.Hit(717, ctx); __imp__sub_82270718(ctx, base); }
REX_HOOK_RAW(sub_82270848) { g_census.Hit(718, ctx); __imp__sub_82270848(ctx, base); }
REX_HOOK_RAW(sub_82270928) { g_census.Hit(719, ctx); __imp__sub_82270928(ctx, base); }
REX_HOOK_RAW(sub_822709C0) { g_census.Hit(720, ctx); __imp__sub_822709C0(ctx, base); }
REX_HOOK_RAW(sub_82270A78) { g_census.Hit(721, ctx); __imp__sub_82270A78(ctx, base); }
REX_HOOK_RAW(sub_82270C00) { g_census.Hit(722, ctx); __imp__sub_82270C00(ctx, base); }
REX_HOOK_RAW(sub_82270C20) { g_census.Hit(723, ctx); __imp__sub_82270C20(ctx, base); }
REX_HOOK_RAW(sub_82270C28) { g_census.Hit(724, ctx); __imp__sub_82270C28(ctx, base); }
REX_HOOK_RAW(sub_82270C48) { g_census.Hit(725, ctx); __imp__sub_82270C48(ctx, base); }
REX_HOOK_RAW(sub_82270C50) { g_census.Hit(726, ctx); __imp__sub_82270C50(ctx, base); }
REX_HOOK_RAW(sub_82270CB0) { g_census.Hit(727, ctx); __imp__sub_82270CB0(ctx, base); }
REX_HOOK_RAW(sub_82270CC8) { g_census.Hit(728, ctx); __imp__sub_82270CC8(ctx, base); }
REX_HOOK_RAW(sub_82270D38) { g_census.Hit(729, ctx); __imp__sub_82270D38(ctx, base); }
REX_HOOK_RAW(sub_82270D48) { g_census.Hit(730, ctx); __imp__sub_82270D48(ctx, base); }
REX_HOOK_RAW(sub_82270EE0) { g_census.Hit(731, ctx); __imp__sub_82270EE0(ctx, base); }
REX_HOOK_RAW(sub_82270F30) { g_census.Hit(732, ctx); __imp__sub_82270F30(ctx, base); }
REX_HOOK_RAW(sub_82270F38) { g_census.Hit(733, ctx); __imp__sub_82270F38(ctx, base); }
REX_HOOK_RAW(sub_82270F80) { g_census.Hit(734, ctx); __imp__sub_82270F80(ctx, base); }
REX_HOOK_RAW(sub_82271020) { g_census.Hit(735, ctx); __imp__sub_82271020(ctx, base); }
REX_HOOK_RAW(sub_82271098) { g_census.Hit(736, ctx); __imp__sub_82271098(ctx, base); }
REX_HOOK_RAW(sub_822710F8) { g_census.Hit(737, ctx); __imp__sub_822710F8(ctx, base); }
REX_HOOK_RAW(sub_82271150) { g_census.Hit(738, ctx); __imp__sub_82271150(ctx, base); }
REX_HOOK_RAW(sub_822714B8) { g_census.Hit(739, ctx); __imp__sub_822714B8(ctx, base); }
REX_HOOK_RAW(sub_822714E0) { g_census.Hit(740, ctx); __imp__sub_822714E0(ctx, base); }
REX_HOOK_RAW(sub_82271650) { g_census.Hit(741, ctx); __imp__sub_82271650(ctx, base); }
REX_HOOK_RAW(sub_822717A0) { g_census.Hit(742, ctx); __imp__sub_822717A0(ctx, base); }
REX_HOOK_RAW(sub_822718D8) { g_census.Hit(743, ctx); __imp__sub_822718D8(ctx, base); }
REX_HOOK_RAW(sub_822719A0) { g_census.Hit(744, ctx); __imp__sub_822719A0(ctx, base); }
REX_HOOK_RAW(sub_82271A30) { g_census.Hit(745, ctx); __imp__sub_82271A30(ctx, base); }
REX_HOOK_RAW(sub_82271A4C) { g_census.Hit(746, ctx); __imp__sub_82271A4C(ctx, base); }
REX_HOOK_RAW(sub_82271A50) { g_census.Hit(747, ctx); __imp__sub_82271A50(ctx, base); }
REX_HOOK_RAW(sub_82271B20) { g_census.Hit(748, ctx); __imp__sub_82271B20(ctx, base); }
REX_HOOK_RAW(sub_82271BC8) { g_census.Hit(749, ctx); __imp__sub_82271BC8(ctx, base); }
REX_HOOK_RAW(sub_82271C60) { g_census.Hit(750, ctx); __imp__sub_82271C60(ctx, base); }
REX_HOOK_RAW(sub_82271D48) { g_census.Hit(751, ctx); __imp__sub_82271D48(ctx, base); }
REX_HOOK_RAW(sub_82271E08) { g_census.Hit(752, ctx); __imp__sub_82271E08(ctx, base); }
REX_HOOK_RAW(sub_82271F40) { g_census.Hit(753, ctx); __imp__sub_82271F40(ctx, base); }
REX_HOOK_RAW(sub_82271FB8) { g_census.Hit(754, ctx); __imp__sub_82271FB8(ctx, base); }
REX_HOOK_RAW(sub_82272050) { g_census.Hit(755, ctx); __imp__sub_82272050(ctx, base); }
REX_HOOK_RAW(sub_82272258) { g_census.Hit(756, ctx); __imp__sub_82272258(ctx, base); }
REX_HOOK_RAW(sub_82272460) { g_census.Hit(757, ctx); __imp__sub_82272460(ctx, base); }
REX_HOOK_RAW(sub_82272728) { g_census.Hit(758, ctx); __imp__sub_82272728(ctx, base); }
REX_HOOK_RAW(sub_822727B8) { g_census.Hit(759, ctx); __imp__sub_822727B8(ctx, base); }
REX_HOOK_RAW(sub_82272890) { g_census.Hit(760, ctx); __imp__sub_82272890(ctx, base); }
REX_HOOK_RAW(sub_82272CD8) { g_census.Hit(761, ctx); __imp__sub_82272CD8(ctx, base); }
REX_HOOK_RAW(sub_82272FD0) { g_census.Hit(762, ctx); __imp__sub_82272FD0(ctx, base); }
REX_HOOK_RAW(sub_82273030) { g_census.Hit(763, ctx); __imp__sub_82273030(ctx, base); }
REX_HOOK_RAW(sub_82273078) { g_census.Hit(764, ctx); __imp__sub_82273078(ctx, base); }
REX_HOOK_RAW(sub_822730C8) { g_census.Hit(765, ctx); __imp__sub_822730C8(ctx, base); }
REX_HOOK_RAW(sub_822731E0) { g_census.Hit(766, ctx); __imp__sub_822731E0(ctx, base); }
REX_HOOK_RAW(sub_82273230) { g_census.Hit(767, ctx); __imp__sub_82273230(ctx, base); }
REX_HOOK_RAW(sub_82273520) { g_census.Hit(768, ctx); __imp__sub_82273520(ctx, base); }
REX_HOOK_RAW(sub_822736E8) { g_census.Hit(769, ctx); __imp__sub_822736E8(ctx, base); }
REX_HOOK_RAW(sub_82273870) { g_census.Hit(770, ctx); __imp__sub_82273870(ctx, base); }
REX_HOOK_RAW(sub_82273948) { g_census.Hit(771, ctx); __imp__sub_82273948(ctx, base); }
REX_HOOK_RAW(sub_822739B0) { g_census.Hit(772, ctx); __imp__sub_822739B0(ctx, base); }
REX_HOOK_RAW(sub_82273A98) { g_census.Hit(773, ctx); __imp__sub_82273A98(ctx, base); }
REX_HOOK_RAW(sub_82273C88) { g_census.Hit(774, ctx); __imp__sub_82273C88(ctx, base); }
REX_HOOK_RAW(sub_82273D28) { g_census.Hit(775, ctx); __imp__sub_82273D28(ctx, base); }
REX_HOOK_RAW(sub_82273E30) { g_census.Hit(776, ctx); __imp__sub_82273E30(ctx, base); }
REX_HOOK_RAW(sub_82273EC0) { g_census.Hit(777, ctx); __imp__sub_82273EC0(ctx, base); }
REX_HOOK_RAW(sub_82274300) { g_census.Hit(778, ctx); __imp__sub_82274300(ctx, base); }
REX_HOOK_RAW(sub_822744D0) { g_census.Hit(779, ctx); __imp__sub_822744D0(ctx, base); }
REX_HOOK_RAW(sub_82274598) { g_census.Hit(780, ctx); __imp__sub_82274598(ctx, base); }
REX_HOOK_RAW(sub_822745F0) { g_census.Hit(781, ctx); __imp__sub_822745F0(ctx, base); }
REX_HOOK_RAW(sub_82274668) { g_census.Hit(782, ctx); __imp__sub_82274668(ctx, base); }
REX_HOOK_RAW(sub_82274750) { g_census.Hit(783, ctx); __imp__sub_82274750(ctx, base); }
REX_HOOK_RAW(sub_822747A8) { g_census.Hit(784, ctx); __imp__sub_822747A8(ctx, base); }
REX_HOOK_RAW(sub_82274908) { g_census.Hit(785, ctx); __imp__sub_82274908(ctx, base); }
REX_HOOK_RAW(sub_82274A40) { g_census.Hit(786, ctx); __imp__sub_82274A40(ctx, base); }
REX_HOOK_RAW(sub_82274AE0) { g_census.Hit(787, ctx); __imp__sub_82274AE0(ctx, base); }
REX_HOOK_RAW(sub_82274B58) { g_census.Hit(788, ctx); __imp__sub_82274B58(ctx, base); }
REX_HOOK_RAW(sub_82274BA8) { g_census.Hit(789, ctx); __imp__sub_82274BA8(ctx, base); }
REX_HOOK_RAW(sub_82274BE0) { g_census.Hit(790, ctx); __imp__sub_82274BE0(ctx, base); }
REX_HOOK_RAW(sub_82274BF8) { g_census.Hit(791, ctx); __imp__sub_82274BF8(ctx, base); }
REX_HOOK_RAW(sub_82274C48) { g_census.Hit(792, ctx); __imp__sub_82274C48(ctx, base); }
REX_HOOK_RAW(sub_82274C60) { g_census.Hit(793, ctx); __imp__sub_82274C60(ctx, base); }
REX_HOOK_RAW(sub_82274C88) { g_census.Hit(794, ctx); __imp__sub_82274C88(ctx, base); }
REX_HOOK_RAW(sub_82274D10) { g_census.Hit(795, ctx); __imp__sub_82274D10(ctx, base); }
REX_HOOK_RAW(sub_82274D30) { g_census.Hit(796, ctx); __imp__sub_82274D30(ctx, base); }
REX_HOOK_RAW(sub_82274E90) { g_census.Hit(797, ctx); __imp__sub_82274E90(ctx, base); }
REX_HOOK_RAW(sub_82275230) { g_census.Hit(798, ctx); __imp__sub_82275230(ctx, base); }
REX_HOOK_RAW(sub_82275300) { g_census.Hit(799, ctx); __imp__sub_82275300(ctx, base); }
REX_HOOK_RAW(sub_82275308) { g_census.Hit(800, ctx); __imp__sub_82275308(ctx, base); }
REX_HOOK_RAW(sub_82275378) { g_census.Hit(801, ctx); __imp__sub_82275378(ctx, base); }
REX_HOOK_RAW(sub_822753F8) { g_census.Hit(802, ctx); __imp__sub_822753F8(ctx, base); }
REX_HOOK_RAW(sub_82275448) { g_census.Hit(803, ctx); __imp__sub_82275448(ctx, base); }
REX_HOOK_RAW(sub_82275590) { g_census.Hit(804, ctx); __imp__sub_82275590(ctx, base); }
REX_HOOK_RAW(sub_82275938) { g_census.Hit(805, ctx); __imp__sub_82275938(ctx, base); }
REX_HOOK_RAW(sub_822759B0) { g_census.Hit(806, ctx); __imp__sub_822759B0(ctx, base); }
REX_HOOK_RAW(sub_82275A70) { g_census.Hit(807, ctx); __imp__sub_82275A70(ctx, base); }
REX_HOOK_RAW(sub_82275E38) { g_census.Hit(808, ctx); __imp__sub_82275E38(ctx, base); }
REX_HOOK_RAW(sub_82275ED0) { g_census.Hit(809, ctx); __imp__sub_82275ED0(ctx, base); }
REX_HOOK_RAW(sub_82275F28) { g_census.Hit(810, ctx); __imp__sub_82275F28(ctx, base); }
REX_HOOK_RAW(sub_82275F90) { g_census.Hit(811, ctx); __imp__sub_82275F90(ctx, base); }
REX_HOOK_RAW(sub_82276018) { g_census.Hit(812, ctx); __imp__sub_82276018(ctx, base); }
REX_HOOK_RAW(sub_82276140) { g_census.Hit(813, ctx); __imp__sub_82276140(ctx, base); }
REX_HOOK_RAW(sub_82276188) { g_census.Hit(814, ctx); __imp__sub_82276188(ctx, base); }
REX_HOOK_RAW(sub_822761F0) { g_census.Hit(815, ctx); __imp__sub_822761F0(ctx, base); }
REX_HOOK_RAW(sub_82276260) { g_census.Hit(816, ctx); __imp__sub_82276260(ctx, base); }
REX_HOOK_RAW(sub_82276370) { g_census.Hit(817, ctx); __imp__sub_82276370(ctx, base); }
REX_HOOK_RAW(sub_822763F0) { g_census.Hit(818, ctx); __imp__sub_822763F0(ctx, base); }
REX_HOOK_RAW(sub_82276440) { g_census.Hit(819, ctx); __imp__sub_82276440(ctx, base); }
REX_HOOK_RAW(sub_822764E0) { g_census.Hit(820, ctx); __imp__sub_822764E0(ctx, base); }
REX_HOOK_RAW(sub_822764E8) { g_census.Hit(821, ctx); __imp__sub_822764E8(ctx, base); }
REX_HOOK_RAW(sub_82276540) { g_census.Hit(822, ctx); __imp__sub_82276540(ctx, base); }
REX_HOOK_RAW(sub_82276560) { g_census.Hit(823, ctx); __imp__sub_82276560(ctx, base); }
REX_HOOK_RAW(sub_822765A0) { g_census.Hit(824, ctx); __imp__sub_822765A0(ctx, base); }
REX_HOOK_RAW(sub_82276678) { g_census.Hit(825, ctx); __imp__sub_82276678(ctx, base); }
REX_HOOK_RAW(sub_822766C8) { g_census.Hit(826, ctx); __imp__sub_822766C8(ctx, base); }
REX_HOOK_RAW(sub_82276708) { g_census.Hit(827, ctx); __imp__sub_82276708(ctx, base); }
REX_HOOK_RAW(sub_82276748) { g_census.Hit(828, ctx); __imp__sub_82276748(ctx, base); }
REX_HOOK_RAW(sub_822769B0) { g_census.Hit(829, ctx); __imp__sub_822769B0(ctx, base); }
REX_HOOK_RAW(sub_82276FF8) { g_census.Hit(830, ctx); __imp__sub_82276FF8(ctx, base); }
REX_HOOK_RAW(sub_82277148) { g_census.Hit(831, ctx); __imp__sub_82277148(ctx, base); }
REX_HOOK_RAW(sub_82277310) { g_census.Hit(832, ctx); __imp__sub_82277310(ctx, base); }
REX_HOOK_RAW(sub_822774A0) { g_census.Hit(833, ctx); __imp__sub_822774A0(ctx, base); }
REX_HOOK_RAW(sub_82277520) { g_census.Hit(834, ctx); __imp__sub_82277520(ctx, base); }
REX_HOOK_RAW(sub_82277538) { g_census.Hit(835, ctx); __imp__sub_82277538(ctx, base); }
REX_HOOK_RAW(sub_82277670) { g_census.Hit(836, ctx); __imp__sub_82277670(ctx, base); }
REX_HOOK_RAW(sub_82277718) { g_census.Hit(837, ctx); __imp__sub_82277718(ctx, base); }
REX_HOOK_RAW(sub_82277720) { g_census.Hit(838, ctx); __imp__sub_82277720(ctx, base); }
REX_HOOK_RAW(sub_82277778) { g_census.Hit(839, ctx); __imp__sub_82277778(ctx, base); }
REX_HOOK_RAW(sub_822777D0) { g_census.Hit(840, ctx); __imp__sub_822777D0(ctx, base); }
REX_HOOK_RAW(sub_82277820) { g_census.Hit(841, ctx); __imp__sub_82277820(ctx, base); }
REX_HOOK_RAW(sub_822778A8) { g_census.Hit(842, ctx); __imp__sub_822778A8(ctx, base); }
REX_HOOK_RAW(sub_82277930) { g_census.Hit(843, ctx); __imp__sub_82277930(ctx, base); }
REX_HOOK_RAW(sub_82277B70) { g_census.Hit(844, ctx); __imp__sub_82277B70(ctx, base); }
REX_HOOK_RAW(sub_82277C98) { g_census.Hit(845, ctx); __imp__sub_82277C98(ctx, base); }
REX_HOOK_RAW(sub_82277E08) { g_census.Hit(846, ctx); __imp__sub_82277E08(ctx, base); }
REX_HOOK_RAW(sub_82277FE8) { g_census.Hit(847, ctx); __imp__sub_82277FE8(ctx, base); }
REX_HOOK_RAW(sub_82278060) { g_census.Hit(848, ctx); __imp__sub_82278060(ctx, base); }
REX_HOOK_RAW(sub_82278240) { g_census.Hit(849, ctx); __imp__sub_82278240(ctx, base); }
REX_HOOK_RAW(sub_825A3AF8) { g_census.Hit(850, ctx); __imp__sub_825A3AF8(ctx, base); }
REX_HOOK_RAW(sub_825A3BA0) { g_census.Hit(851, ctx); __imp__sub_825A3BA0(ctx, base); }
REX_HOOK_RAW(sub_825A3BA8) { g_census.Hit(852, ctx); __imp__sub_825A3BA8(ctx, base); }
REX_HOOK_RAW(sub_825A3C48) { g_census.Hit(853, ctx); __imp__sub_825A3C48(ctx, base); }
REX_HOOK_RAW(sub_825A3CD0) { g_census.Hit(854, ctx); __imp__sub_825A3CD0(ctx, base); }
REX_HOOK_RAW(sub_825A3E98) { g_census.Hit(855, ctx); __imp__sub_825A3E98(ctx, base); }
REX_HOOK_RAW(sub_825A4330) { g_census.Hit(856, ctx); __imp__sub_825A4330(ctx, base); }
REX_HOOK_RAW(sub_825A4340) { g_census.Hit(857, ctx); __imp__sub_825A4340(ctx, base); }
REX_HOOK_RAW(sub_825A4790) { g_census.Hit(858, ctx); __imp__sub_825A4790(ctx, base); }
REX_HOOK_RAW(sub_825A47D8) { g_census.Hit(859, ctx); __imp__sub_825A47D8(ctx, base); }
REX_HOOK_RAW(sub_825A4808) { g_census.Hit(860, ctx); __imp__sub_825A4808(ctx, base); }
REX_HOOK_RAW(sub_825A4868) { g_census.Hit(861, ctx); __imp__sub_825A4868(ctx, base); }
REX_HOOK_RAW(sub_825A4F18) { g_census.Hit(862, ctx); __imp__sub_825A4F18(ctx, base); }
